package pe.gob.ep.ginnet.seguridad.dao;

import java.util.List;

import pe.gob.ep.ginnet.seguridad.bean.Opcion;
import pe.gob.ep.ginnet.seguridad.bean.OpcionCriteria;

public interface OpcionDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    int countByExample(OpcionCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    int deleteByExample(OpcionCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    int deleteByPrimaryKey(Integer iOpcionId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    void insert(Opcion record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    void insertSelective(Opcion record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    List<Opcion> selectByExample(OpcionCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    Opcion selectByPrimaryKey(Integer iOpcionId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    int updateByExampleSelective(Opcion record, OpcionCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    int updateByExample(Opcion record, OpcionCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKeySelective(Opcion record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKey(Opcion record);
}