package pe.gob.ep.ginnet.seguridad.dao;

import java.util.List;

import pe.gob.ep.ginnet.seguridad.bean.Rol;
import pe.gob.ep.ginnet.seguridad.bean.RolCriteria;

public interface RolDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rol
     *
     * @ibatorgenerated
     */
    int countByExample(RolCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rol
     *
     * @ibatorgenerated
     */
    int deleteByExample(RolCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rol
     *
     * @ibatorgenerated
     */
    int deleteByPrimaryKey(Integer iRolId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rol
     *
     * @ibatorgenerated
     */
    void insert(Rol record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rol
     *
     * @ibatorgenerated
     */
    void insertSelective(Rol record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rol
     *
     * @ibatorgenerated
     */
    List<Rol> selectByExample(RolCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rol
     *
     * @ibatorgenerated
     */
    Rol selectByPrimaryKey(Integer iRolId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rol
     *
     * @ibatorgenerated
     */
    int updateByExampleSelective(Rol record, RolCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rol
     *
     * @ibatorgenerated
     */
    int updateByExample(Rol record, RolCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rol
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKeySelective(Rol record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rol
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKey(Rol record);
}