package pe.gob.ep.ginnet.seguridad.dao;

import java.util.List;
import java.util.Map;

import pe.gob.ep.ginnet.seguridad.bean.RolOpcion;
import pe.gob.ep.ginnet.seguridad.bean.RolOpcionCriteria;

public interface RolOpcionDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rolxopcion
     *
     * @ibatorgenerated
     */
    int countByExample(RolOpcionCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rolxopcion
     *
     * @ibatorgenerated
     */
    int deleteByExample(RolOpcionCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rolxopcion
     *
     * @ibatorgenerated
     */
    int deleteByPrimaryKey(Integer iRolxopcionId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rolxopcion
     *
     * @ibatorgenerated
     */
    void insert(RolOpcion record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rolxopcion
     *
     * @ibatorgenerated
     */
    void insertSelective(RolOpcion record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rolxopcion
     *
     * @ibatorgenerated
     */
    List<RolOpcion> selectByExample(RolOpcionCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rolxopcion
     *
     * @ibatorgenerated
     */
    RolOpcion selectByPrimaryKey(Integer iRolxopcionId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rolxopcion
     *
     * @ibatorgenerated
     */
    int updateByExampleSelective(RolOpcion record, RolOpcionCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rolxopcion
     *
     * @ibatorgenerated
     */
    int updateByExample(RolOpcion record, RolOpcionCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rolxopcion
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKeySelective(RolOpcion record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rolxopcion
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKey(RolOpcion record);
    
    /**
	 * Este metodo obtiene la lista de opciones del sistema por rol
	 * @author Willian Pillaca
	 */
	List<Map<String, Object>> selectMenu(Map<String, Object> params);
	
	/**
	 * Este metodo obtiene la lista de opciones por rol para el mantenimiento de opciones por rol
	 * @author Willian Pillaca
	 */
	List<Map<String, Object>> selectTreeRolOpcion(Map<String, Object> params);
}