package pe.gob.ep.ginnet.seguridad.dao.ibatis;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.ginnet.seguridad.bean.Opcion;
import pe.gob.ep.ginnet.seguridad.bean.OpcionCriteria;
import pe.gob.ep.ginnet.seguridad.dao.OpcionDAO;

public class OpcionDAOImpl extends SqlMapClientDaoSupport implements OpcionDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    public OpcionDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    public int countByExample(OpcionCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("ctrl_seg_opcion.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    public int deleteByExample(OpcionCriteria example) {
        int rows = getSqlMapClientTemplate().delete("ctrl_seg_opcion.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer iOpcionId) {
        Opcion key = new Opcion();
        key.setiOpcionId(iOpcionId);
        int rows = getSqlMapClientTemplate().delete("ctrl_seg_opcion.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    public void insert(Opcion record) {
        getSqlMapClientTemplate().insert("ctrl_seg_opcion.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    public void insertSelective(Opcion record) {
        getSqlMapClientTemplate().insert("ctrl_seg_opcion.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<Opcion> selectByExample(OpcionCriteria example) {
        List<Opcion> list = getSqlMapClientTemplate().queryForList("ctrl_seg_opcion.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    public Opcion selectByPrimaryKey(Integer iOpcionId) {
        Opcion key = new Opcion();
        key.setiOpcionId(iOpcionId);
        Opcion record = (Opcion) getSqlMapClientTemplate().queryForObject("ctrl_seg_opcion.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(Opcion record, OpcionCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("ctrl_seg_opcion.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    public int updateByExample(Opcion record, OpcionCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("ctrl_seg_opcion.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(Opcion record) {
        int rows = getSqlMapClientTemplate().update("ctrl_seg_opcion.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(Opcion record) {
        int rows = getSqlMapClientTemplate().update("ctrl_seg_opcion.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends OpcionCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, OpcionCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}