package pe.gob.ep.ginnet.seguridad.dao.ibatis;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.ginnet.seguridad.bean.Rol;
import pe.gob.ep.ginnet.seguridad.bean.RolCriteria;
import pe.gob.ep.ginnet.seguridad.dao.RolDAO;

public class RolDAOImpl extends SqlMapClientDaoSupport implements RolDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rol
     *
     * @ibatorgenerated
     */
    public RolDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rol
     *
     * @ibatorgenerated
     */
    public int countByExample(RolCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("ctrl_seg_rol.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rol
     *
     * @ibatorgenerated
     */
    public int deleteByExample(RolCriteria example) {
        int rows = getSqlMapClientTemplate().delete("ctrl_seg_rol.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rol
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer iRolId) {
        Rol key = new Rol();
        key.setiRolId(iRolId);
        int rows = getSqlMapClientTemplate().delete("ctrl_seg_rol.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rol
     *
     * @ibatorgenerated
     */
    public void insert(Rol record) {
        getSqlMapClientTemplate().insert("ctrl_seg_rol.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rol
     *
     * @ibatorgenerated
     */
    public void insertSelective(Rol record) {
        getSqlMapClientTemplate().insert("ctrl_seg_rol.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rol
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<Rol> selectByExample(RolCriteria example) {
        List<Rol> list = getSqlMapClientTemplate().queryForList("ctrl_seg_rol.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rol
     *
     * @ibatorgenerated
     */
    public Rol selectByPrimaryKey(Integer iRolId) {
        Rol key = new Rol();
        key.setiRolId(iRolId);
        Rol record = (Rol) getSqlMapClientTemplate().queryForObject("ctrl_seg_rol.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rol
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(Rol record, RolCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("ctrl_seg_rol.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rol
     *
     * @ibatorgenerated
     */
    public int updateByExample(Rol record, RolCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("ctrl_seg_rol.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rol
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(Rol record) {
        int rows = getSqlMapClientTemplate().update("ctrl_seg_rol.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rol
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(Rol record) {
        int rows = getSqlMapClientTemplate().update("ctrl_seg_rol.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table ctrl_seg_rol
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends RolCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, RolCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}