package pe.gob.ep.ginnet.seguridad.dao.ibatis;

import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.ginnet.seguridad.bean.RolOpcion;
import pe.gob.ep.ginnet.seguridad.bean.RolOpcionCriteria;
import pe.gob.ep.ginnet.seguridad.dao.RolOpcionDAO;

public class RolOpcionDAOImpl extends SqlMapClientDaoSupport implements RolOpcionDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rolxopcion
     *
     * @ibatorgenerated
     */
    public RolOpcionDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rolxopcion
     *
     * @ibatorgenerated
     */
    public int countByExample(RolOpcionCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("ctrl_seg_rolxopcion.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rolxopcion
     *
     * @ibatorgenerated
     */
    public int deleteByExample(RolOpcionCriteria example) {
        int rows = getSqlMapClientTemplate().delete("ctrl_seg_rolxopcion.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rolxopcion
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer iRolxopcionId) {
        RolOpcion key = new RolOpcion();
        key.setiRolxopcionId(iRolxopcionId);
        int rows = getSqlMapClientTemplate().delete("ctrl_seg_rolxopcion.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rolxopcion
     *
     * @ibatorgenerated
     */
    public void insert(RolOpcion record) {
        getSqlMapClientTemplate().insert("ctrl_seg_rolxopcion.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rolxopcion
     *
     * @ibatorgenerated
     */
    public void insertSelective(RolOpcion record) {
        getSqlMapClientTemplate().insert("ctrl_seg_rolxopcion.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rolxopcion
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<RolOpcion> selectByExample(RolOpcionCriteria example) {
        List<RolOpcion> list = getSqlMapClientTemplate().queryForList("ctrl_seg_rolxopcion.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rolxopcion
     *
     * @ibatorgenerated
     */
    public RolOpcion selectByPrimaryKey(Integer iRolxopcionId) {
        RolOpcion key = new RolOpcion();
        key.setiRolxopcionId(iRolxopcionId);
        RolOpcion record = (RolOpcion) getSqlMapClientTemplate().queryForObject("ctrl_seg_rolxopcion.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rolxopcion
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(RolOpcion record, RolOpcionCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("ctrl_seg_rolxopcion.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rolxopcion
     *
     * @ibatorgenerated
     */
    public int updateByExample(RolOpcion record, RolOpcionCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("ctrl_seg_rolxopcion.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rolxopcion
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(RolOpcion record) {
        int rows = getSqlMapClientTemplate().update("ctrl_seg_rolxopcion.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_rolxopcion
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(RolOpcion record) {
        int rows = getSqlMapClientTemplate().update("ctrl_seg_rolxopcion.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table ctrl_seg_rolxopcion
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends RolOpcionCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, RolOpcionCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
    
    @Override
	public List<Map<String, Object>> selectMenu(Map<String, Object> params) {
		// TODO Auto-generated method stub
		List<Map<String, Object>> list = getSqlMapClientTemplate().queryForList("ctrl_seg_rolxopcion.selectMenu", params);
		return list;
	}

	@Override
	public List<Map<String, Object>> selectTreeRolOpcion(
			Map<String, Object> params) {
		// TODO Auto-generated method stub
		List<Map<String, Object>> list = getSqlMapClientTemplate().queryForList("ctrl_seg_rolxopcion.selectTreeRolOpcion", params);
		return list;
	}
}