package pe.gob.ep.ginnet.seguridad.dao.ibatis;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.ginnet.seguridad.bean.UsuarioRol;
import pe.gob.ep.ginnet.seguridad.bean.UsuarioRolCriteria;
import pe.gob.ep.ginnet.seguridad.dao.UsuarioRolDAO;

public class UsuarioRolDAOImpl extends SqlMapClientDaoSupport implements UsuarioRolDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuarioxrol
     *
     * @ibatorgenerated
     */
    public UsuarioRolDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuarioxrol
     *
     * @ibatorgenerated
     */
    public int countByExample(UsuarioRolCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("ctrl_seg_usuarioxrol.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuarioxrol
     *
     * @ibatorgenerated
     */
    public int deleteByExample(UsuarioRolCriteria example) {
        int rows = getSqlMapClientTemplate().delete("ctrl_seg_usuarioxrol.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuarioxrol
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer iUsuarioxrolId) {
        UsuarioRol key = new UsuarioRol();
        key.setiUsuarioxrolId(iUsuarioxrolId);
        int rows = getSqlMapClientTemplate().delete("ctrl_seg_usuarioxrol.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuarioxrol
     *
     * @ibatorgenerated
     */
    public void insert(UsuarioRol record) {
        getSqlMapClientTemplate().insert("ctrl_seg_usuarioxrol.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuarioxrol
     *
     * @ibatorgenerated
     */
    public void insertSelective(UsuarioRol record) {
        getSqlMapClientTemplate().insert("ctrl_seg_usuarioxrol.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuarioxrol
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<UsuarioRol> selectByExample(UsuarioRolCriteria example) {
        List<UsuarioRol> list = getSqlMapClientTemplate().queryForList("ctrl_seg_usuarioxrol.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuarioxrol
     *
     * @ibatorgenerated
     */
    public UsuarioRol selectByPrimaryKey(Integer iUsuarioxrolId) {
        UsuarioRol key = new UsuarioRol();
        key.setiUsuarioxrolId(iUsuarioxrolId);
        UsuarioRol record = (UsuarioRol) getSqlMapClientTemplate().queryForObject("ctrl_seg_usuarioxrol.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuarioxrol
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(UsuarioRol record, UsuarioRolCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("ctrl_seg_usuarioxrol.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuarioxrol
     *
     * @ibatorgenerated
     */
    public int updateByExample(UsuarioRol record, UsuarioRolCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("ctrl_seg_usuarioxrol.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuarioxrol
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(UsuarioRol record) {
        int rows = getSqlMapClientTemplate().update("ctrl_seg_usuarioxrol.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuarioxrol
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(UsuarioRol record) {
        int rows = getSqlMapClientTemplate().update("ctrl_seg_usuarioxrol.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table ctrl_seg_usuarioxrol
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends UsuarioRolCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, UsuarioRolCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}