package pe.gob.ep.ginnet.seguridad.dao.ibatis;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.ginnet.seguridad.bean.Usuario;
import pe.gob.ep.ginnet.seguridad.bean.UsuarioCriteria;
import pe.gob.ep.ginnet.seguridad.dao.UsuarioDAO;

public class UsuarioDAOImpl extends SqlMapClientDaoSupport implements UsuarioDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuario
     *
     * @ibatorgenerated
     */
    public UsuarioDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuario
     *
     * @ibatorgenerated
     */
    public int countByExample(UsuarioCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("ctrl_seg_usuario.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuario
     *
     * @ibatorgenerated
     */
    public int deleteByExample(UsuarioCriteria example) {
        int rows = getSqlMapClientTemplate().delete("ctrl_seg_usuario.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuario
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer iUsuarioId) {
        Usuario key = new Usuario();
        key.setiUsuarioId(iUsuarioId);
        int rows = getSqlMapClientTemplate().delete("ctrl_seg_usuario.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuario
     *
     * @ibatorgenerated
     */
    public void insert(Usuario record) {
        getSqlMapClientTemplate().insert("ctrl_seg_usuario.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuario
     *
     * @ibatorgenerated
     */
    public void insertSelective(Usuario record) {
        getSqlMapClientTemplate().insert("ctrl_seg_usuario.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuario
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<Usuario> selectByExample(UsuarioCriteria example) {
        List<Usuario> list = getSqlMapClientTemplate().queryForList("ctrl_seg_usuario.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuario
     *
     * @ibatorgenerated
     */
    public Usuario selectByPrimaryKey(Integer iUsuarioId) {
        Usuario key = new Usuario();
        key.setiUsuarioId(iUsuarioId);
        Usuario record = (Usuario) getSqlMapClientTemplate().queryForObject("ctrl_seg_usuario.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuario
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(Usuario record, UsuarioCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("ctrl_seg_usuario.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuario
     *
     * @ibatorgenerated
     */
    public int updateByExample(Usuario record, UsuarioCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("ctrl_seg_usuario.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuario
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(Usuario record) {
        int rows = getSqlMapClientTemplate().update("ctrl_seg_usuario.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuario
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(Usuario record) {
        int rows = getSqlMapClientTemplate().update("ctrl_seg_usuario.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table ctrl_seg_usuario
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends UsuarioCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, UsuarioCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public List<Usuario> listarDocentes(int param) {
		// TODO Auto-generated method stub
		List<Usuario> list = getSqlMapClientTemplate().queryForList("ctrl_seg_usuario.listarDocentes", param);
        return list;
	}
}