package pe.gob.ep.ginnet.radamanthys.dao;

import java.util.List;
import java.util.Map;

import pe.gob.ep.ginnet.radamanthys.bean.Alternativa;
import pe.gob.ep.ginnet.radamanthys.bean.Examen;
import pe.gob.ep.ginnet.radamanthys.bean.ExamenCriteria;

public interface ExamenDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_examen
     *
     * @ibatorgenerated
     */
    int countByExample(ExamenCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_examen
     *
     * @ibatorgenerated
     */
    int deleteByExample(ExamenCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_examen
     *
     * @ibatorgenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_examen
     *
     * @ibatorgenerated
     */
    void insert(Examen record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_examen
     *
     * @ibatorgenerated
     */
    void insertSelective(Examen record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_examen
     *
     * @ibatorgenerated
     */
    List<Examen> selectByExample(ExamenCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_examen
     *
     * @ibatorgenerated
     */
    Examen selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_examen
     *
     * @ibatorgenerated
     */
    int updateByExampleSelective(Examen record, ExamenCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_examen
     *
     * @ibatorgenerated
     */
    int updateByExample(Examen record, ExamenCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_examen
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKeySelective(Examen record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_examen
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKey(Examen record);
    
    /**metodos agregados**/
    
    List<Examen> listarPreguntasExamen(Map<String, Object> params);
    
    List<Examen> obtenerIdPregunta(Map<String, Object> params);
    
    
}