package pe.gob.ep.ginnet.radamanthys.dao;

import java.util.List;
import java.util.Map;

import pe.gob.ep.ginnet.radamanthys.bean.Persona;
import pe.gob.ep.ginnet.radamanthys.bean.PersonaCriteria;

public interface PersonaDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_persona
     *
     * @ibatorgenerated
     */
    int countByExample(PersonaCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_persona
     *
     * @ibatorgenerated
     */
    int deleteByExample(PersonaCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_persona
     *
     * @ibatorgenerated
     */
    int deleteByPrimaryKey(Integer codigo);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_persona
     *
     * @ibatorgenerated
     */
    void insert(Persona record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_persona
     *
     * @ibatorgenerated
     */
    void insertSelective(Persona record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_persona
     *
     * @ibatorgenerated
     */
    List<Persona> selectByExample(PersonaCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_persona
     *
     * @ibatorgenerated
     */
    Persona selectByPrimaryKey(Integer codigo);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_persona
     *
     * @ibatorgenerated
     */
    int updateByExampleSelective(Persona record, PersonaCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_persona
     *
     * @ibatorgenerated
     */
    int updateByExample(Persona record, PersonaCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_persona
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKeySelective(Persona record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_persona
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKey(Persona record);
    
    Persona validateUser(Map<String, Object> params) throws Exception;
}