package pe.gob.ep.ginnet.radamanthys.dao;

import java.util.List;
import java.util.Map;

import pe.gob.ep.ginnet.radamanthys.bean.Pregunta;
import pe.gob.ep.ginnet.radamanthys.bean.PreguntaCriteria;

public interface PreguntaDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_pregunta
     *
     * @ibatorgenerated
     */
    int countByExample(PreguntaCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_pregunta
     *
     * @ibatorgenerated
     */
    int deleteByExample(PreguntaCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_pregunta
     *
     * @ibatorgenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_pregunta
     *
     * @ibatorgenerated
     */
    void insert(Pregunta record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_pregunta
     *
     * @ibatorgenerated
     */
    void insertSelective(Pregunta record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_pregunta
     *
     * @ibatorgenerated
     */
    List<Pregunta> selectByExample(PreguntaCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_pregunta
     *
     * @ibatorgenerated
     */
    Pregunta selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_pregunta
     *
     * @ibatorgenerated
     */
    int updateByExampleSelective(Pregunta record, PreguntaCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_pregunta
     *
     * @ibatorgenerated
     */
    int updateByExample(Pregunta record, PreguntaCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_pregunta
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKeySelective(Pregunta record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_pregunta
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKey(Pregunta record);
    
    List<Map<String, Object>> getAllPreguntas(Map<String, Object> params);
    
    List<Map<String, Object>> getAllPreguntasXTema(Map<String, Object> params);
    
    List<Map<String, Object>> getPreguntasByCodigoCurso(Map<String, Object> params);
    
    List<Map<String, Object>> getPreguntaAbiertaByCodigoCurso(Map<String, Object> params);
    
}