package pe.gob.ep.ginnet.radamanthys.dao;

import java.util.List;

import pe.gob.ep.ginnet.radamanthys.bean.Profesor;
import pe.gob.ep.ginnet.radamanthys.bean.ProfesorCriteria;

public interface ProfesorDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_profesor
     *
     * @ibatorgenerated
     */
    int countByExample(ProfesorCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_profesor
     *
     * @ibatorgenerated
     */
    int deleteByExample(ProfesorCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_profesor
     *
     * @ibatorgenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_profesor
     *
     * @ibatorgenerated
     */
    void insert(Profesor record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_profesor
     *
     * @ibatorgenerated
     */
    void insertSelective(Profesor record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_profesor
     *
     * @ibatorgenerated
     */
    List<Profesor> selectByExample(ProfesorCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_profesor
     *
     * @ibatorgenerated
     */
    Profesor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_profesor
     *
     * @ibatorgenerated
     */
    int updateByExampleSelective(Profesor record, ProfesorCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_profesor
     *
     * @ibatorgenerated
     */
    int updateByExample(Profesor record, ProfesorCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_profesor
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKeySelective(Profesor record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_profesor
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKey(Profesor record);
}