package pe.gob.ep.ginnet.radamanthys.dao;

import java.util.List;

import pe.gob.ep.ginnet.radamanthys.bean.Prueba;
import pe.gob.ep.ginnet.radamanthys.bean.PruebaCriteria;

public interface PruebaDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prueba
     *
     * @ibatorgenerated
     */
    int countByExample(PruebaCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prueba
     *
     * @ibatorgenerated
     */
    int deleteByExample(PruebaCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prueba
     *
     * @ibatorgenerated
     */
    int deleteByPrimaryKey(Integer idNombre);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prueba
     *
     * @ibatorgenerated
     */
    void insert(Prueba record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prueba
     *
     * @ibatorgenerated
     */
    void insertSelective(Prueba record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prueba
     *
     * @ibatorgenerated
     */
    List<Prueba> selectByExample(PruebaCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prueba
     *
     * @ibatorgenerated
     */
    Prueba selectByPrimaryKey(Integer idNombre);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prueba
     *
     * @ibatorgenerated
     */
    int updateByExampleSelective(Prueba record, PruebaCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prueba
     *
     * @ibatorgenerated
     */
    int updateByExample(Prueba record, PruebaCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prueba
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKeySelective(Prueba record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prueba
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKey(Prueba record);
}