package pe.gob.ep.ginnet.radamanthys.dao;

import java.util.List;
import java.util.Map;

import pe.gob.ep.ginnet.radamanthys.bean.Tema;
import pe.gob.ep.ginnet.radamanthys.bean.TemaCriteria;

public interface TemaDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_tema
     *
     * @ibatorgenerated
     */
    int countByExample(TemaCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_tema
     *
     * @ibatorgenerated
     */
    int deleteByExample(TemaCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_tema
     *
     * @ibatorgenerated
     */
    int deleteByPrimaryKey(Integer idTema);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_tema
     *
     * @ibatorgenerated
     */
    void insert(Tema record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_tema
     *
     * @ibatorgenerated
     */
    void insertSelective(Tema record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_tema
     *
     * @ibatorgenerated
     */
    List<Tema> selectByExample(TemaCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_tema
     *
     * @ibatorgenerated
     */
    Tema selectByPrimaryKey(Integer idTema);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_tema
     *
     * @ibatorgenerated
     */
    int updateByExampleSelective(Tema record, TemaCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_tema
     *
     * @ibatorgenerated
     */
    int updateByExample(Tema record, TemaCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_tema
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKeySelective(Tema record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_tema
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKey(Tema record);
    
    List<Map<String, Object>> getTemasByCodigoCurso(Map<String, Object> params);
    
}