package pe.gob.ep.ginnet.catalogo.bean;

import java.math.BigDecimal;

public class ElementoCatalogo {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column WILLIAN.CTRL_CONF_CATALOGO.I_CATALOGO_ID
     *
     * @ibatorgenerated
     */
    private Integer iCatalogoId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_NOMBRE
     *
     * @ibatorgenerated
     */
    private String vCatalogoNombre;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_DEFINICION
     *
     * @ibatorgenerated
     */
    private String vCatalogoDefinicion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_ABREVIATURA
     *
     * @ibatorgenerated
     */
    private String vCatalogoAbreviatura;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_DESPARAM1
     *
     * @ibatorgenerated
     */
    private String vCatalogoDesparam1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_DESPARAM2
     *
     * @ibatorgenerated
     */
    private String vCatalogoDesparam2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_DESPARAM3
     *
     * @ibatorgenerated
     */
    private String vCatalogoDesparam3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_DESPARAM4
     *
     * @ibatorgenerated
     */
    private String vCatalogoDesparam4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column WILLIAN.CTRL_CONF_CATALOGO.I_CATALOGO_GRUPO_ID
     *
     * @ibatorgenerated
     */
    private Integer iCatalogoGrupoId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column WILLIAN.CTRL_CONF_CATALOGO.I_CATALOGO_ESTADO
     *
     * @ibatorgenerated
     */
    private Integer iCatalogoEstado;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column WILLIAN.CTRL_CONF_CATALOGO.I_CATALOGO_ID
     *
     * @return the value of WILLIAN.CTRL_CONF_CATALOGO.I_CATALOGO_ID
     *
     * @ibatorgenerated
     */
    public Integer getiCatalogoId() {
        return iCatalogoId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column WILLIAN.CTRL_CONF_CATALOGO.I_CATALOGO_ID
     *
     * @param iCatalogoId the value for WILLIAN.CTRL_CONF_CATALOGO.I_CATALOGO_ID
     *
     * @ibatorgenerated
     */
    public void setiCatalogoId(Integer iCatalogoId) {
        this.iCatalogoId = iCatalogoId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_NOMBRE
     *
     * @return the value of WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_NOMBRE
     *
     * @ibatorgenerated
     */
    public String getvCatalogoNombre() {
        return vCatalogoNombre;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_NOMBRE
     *
     * @param vCatalogoNombre the value for WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_NOMBRE
     *
     * @ibatorgenerated
     */
    public void setvCatalogoNombre(String vCatalogoNombre) {
        this.vCatalogoNombre = vCatalogoNombre;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_DEFINICION
     *
     * @return the value of WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_DEFINICION
     *
     * @ibatorgenerated
     */
    public String getvCatalogoDefinicion() {
        return vCatalogoDefinicion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_DEFINICION
     *
     * @param vCatalogoDefinicion the value for WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_DEFINICION
     *
     * @ibatorgenerated
     */
    public void setvCatalogoDefinicion(String vCatalogoDefinicion) {
        this.vCatalogoDefinicion = vCatalogoDefinicion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_ABREVIATURA
     *
     * @return the value of WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_ABREVIATURA
     *
     * @ibatorgenerated
     */
    public String getvCatalogoAbreviatura() {
        return vCatalogoAbreviatura;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_ABREVIATURA
     *
     * @param vCatalogoAbreviatura the value for WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_ABREVIATURA
     *
     * @ibatorgenerated
     */
    public void setvCatalogoAbreviatura(String vCatalogoAbreviatura) {
        this.vCatalogoAbreviatura = vCatalogoAbreviatura;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_DESPARAM1
     *
     * @return the value of WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_DESPARAM1
     *
     * @ibatorgenerated
     */
    public String getvCatalogoDesparam1() {
        return vCatalogoDesparam1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_DESPARAM1
     *
     * @param vCatalogoDesparam1 the value for WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_DESPARAM1
     *
     * @ibatorgenerated
     */
    public void setvCatalogoDesparam1(String vCatalogoDesparam1) {
        this.vCatalogoDesparam1 = vCatalogoDesparam1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_DESPARAM2
     *
     * @return the value of WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_DESPARAM2
     *
     * @ibatorgenerated
     */
    public String getvCatalogoDesparam2() {
        return vCatalogoDesparam2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_DESPARAM2
     *
     * @param vCatalogoDesparam2 the value for WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_DESPARAM2
     *
     * @ibatorgenerated
     */
    public void setvCatalogoDesparam2(String vCatalogoDesparam2) {
        this.vCatalogoDesparam2 = vCatalogoDesparam2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_DESPARAM3
     *
     * @return the value of WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_DESPARAM3
     *
     * @ibatorgenerated
     */
    public String getvCatalogoDesparam3() {
        return vCatalogoDesparam3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_DESPARAM3
     *
     * @param vCatalogoDesparam3 the value for WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_DESPARAM3
     *
     * @ibatorgenerated
     */
    public void setvCatalogoDesparam3(String vCatalogoDesparam3) {
        this.vCatalogoDesparam3 = vCatalogoDesparam3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_DESPARAM4
     *
     * @return the value of WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_DESPARAM4
     *
     * @ibatorgenerated
     */
    public String getvCatalogoDesparam4() {
        return vCatalogoDesparam4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_DESPARAM4
     *
     * @param vCatalogoDesparam4 the value for WILLIAN.CTRL_CONF_CATALOGO.V_CATALOGO_DESPARAM4
     *
     * @ibatorgenerated
     */
    public void setvCatalogoDesparam4(String vCatalogoDesparam4) {
        this.vCatalogoDesparam4 = vCatalogoDesparam4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column WILLIAN.CTRL_CONF_CATALOGO.I_CATALOGO_GRUPO_ID
     *
     * @return the value of WILLIAN.CTRL_CONF_CATALOGO.I_CATALOGO_GRUPO_ID
     *
     * @ibatorgenerated
     */
    public Integer getiCatalogoGrupoId() {
        return iCatalogoGrupoId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column WILLIAN.CTRL_CONF_CATALOGO.I_CATALOGO_GRUPO_ID
     *
     * @param iCatalogoGrupoId the value for WILLIAN.CTRL_CONF_CATALOGO.I_CATALOGO_GRUPO_ID
     *
     * @ibatorgenerated
     */
    public void setiCatalogoGrupoId(Integer iCatalogoGrupoId) {
        this.iCatalogoGrupoId = iCatalogoGrupoId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column WILLIAN.CTRL_CONF_CATALOGO.I_CATALOGO_ESTADO
     *
     * @return the value of WILLIAN.CTRL_CONF_CATALOGO.I_CATALOGO_ESTADO
     *
     * @ibatorgenerated
     */
    public Integer getiCatalogoEstado() {
        return iCatalogoEstado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column WILLIAN.CTRL_CONF_CATALOGO.I_CATALOGO_ESTADO
     *
     * @param iCatalogoEstado the value for WILLIAN.CTRL_CONF_CATALOGO.I_CATALOGO_ESTADO
     *
     * @ibatorgenerated
     */
    public void setiCatalogoEstado(Integer iCatalogoEstado) {
        this.iCatalogoEstado = iCatalogoEstado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WILLIAN.CTRL_CONF_CATALOGO
     *
     * @ibatorgenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof ElementoCatalogo)) {
            return false;
        }
        ElementoCatalogo other = (ElementoCatalogo) that;
        return this.getiCatalogoId() == null ? other == null : this.getiCatalogoId().equals(other.getiCatalogoId())
            && this.getvCatalogoNombre() == null ? other == null : this.getvCatalogoNombre().equals(other.getvCatalogoNombre())
            && this.getvCatalogoDefinicion() == null ? other == null : this.getvCatalogoDefinicion().equals(other.getvCatalogoDefinicion())
            && this.getvCatalogoAbreviatura() == null ? other == null : this.getvCatalogoAbreviatura().equals(other.getvCatalogoAbreviatura())
            && this.getvCatalogoDesparam1() == null ? other == null : this.getvCatalogoDesparam1().equals(other.getvCatalogoDesparam1())
            && this.getvCatalogoDesparam2() == null ? other == null : this.getvCatalogoDesparam2().equals(other.getvCatalogoDesparam2())
            && this.getvCatalogoDesparam3() == null ? other == null : this.getvCatalogoDesparam3().equals(other.getvCatalogoDesparam3())
            && this.getvCatalogoDesparam4() == null ? other == null : this.getvCatalogoDesparam4().equals(other.getvCatalogoDesparam4())
            && this.getiCatalogoGrupoId() == null ? other == null : this.getiCatalogoGrupoId().equals(other.getiCatalogoGrupoId())
            && this.getiCatalogoEstado() == null ? other == null : this.getiCatalogoEstado().equals(other.getiCatalogoEstado());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WILLIAN.CTRL_CONF_CATALOGO
     *
     * @ibatorgenerated
     */
    @Override
    public int hashCode() {
        int hash = 23;
        if (getiCatalogoId() != null) {
            hash *= getiCatalogoId().hashCode();
        }
        if (getvCatalogoNombre() != null) {
            hash *= getvCatalogoNombre().hashCode();
        }
        if (getvCatalogoDefinicion() != null) {
            hash *= getvCatalogoDefinicion().hashCode();
        }
        if (getvCatalogoAbreviatura() != null) {
            hash *= getvCatalogoAbreviatura().hashCode();
        }
        if (getvCatalogoDesparam1() != null) {
            hash *= getvCatalogoDesparam1().hashCode();
        }
        if (getvCatalogoDesparam2() != null) {
            hash *= getvCatalogoDesparam2().hashCode();
        }
        if (getvCatalogoDesparam3() != null) {
            hash *= getvCatalogoDesparam3().hashCode();
        }
        if (getvCatalogoDesparam4() != null) {
            hash *= getvCatalogoDesparam4().hashCode();
        }
        if (getiCatalogoGrupoId() != null) {
            hash *= getiCatalogoGrupoId().hashCode();
        }
        if (getiCatalogoEstado() != null) {
            hash *= getiCatalogoEstado().hashCode();
        }
        return hash;
    }
}