package pe.gob.ep.ginnet.seguridad.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class OpcionCriteria {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    public OpcionCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    protected OpcionCriteria(OpcionCriteria example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table ctrl_seg_opcion
     *
     * @ibatorgenerated
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIOpcionIdIsNull() {
            addCriterion("I_OPCION_ID is null");
            return this;
        }

        public Criteria andIOpcionIdIsNotNull() {
            addCriterion("I_OPCION_ID is not null");
            return this;
        }

        public Criteria andIOpcionIdEqualTo(Integer value) {
            addCriterion("I_OPCION_ID =", value, "iOpcionId");
            return this;
        }

        public Criteria andIOpcionIdNotEqualTo(Integer value) {
            addCriterion("I_OPCION_ID <>", value, "iOpcionId");
            return this;
        }

        public Criteria andIOpcionIdGreaterThan(Integer value) {
            addCriterion("I_OPCION_ID >", value, "iOpcionId");
            return this;
        }

        public Criteria andIOpcionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("I_OPCION_ID >=", value, "iOpcionId");
            return this;
        }

        public Criteria andIOpcionIdLessThan(Integer value) {
            addCriterion("I_OPCION_ID <", value, "iOpcionId");
            return this;
        }

        public Criteria andIOpcionIdLessThanOrEqualTo(Integer value) {
            addCriterion("I_OPCION_ID <=", value, "iOpcionId");
            return this;
        }

        public Criteria andIOpcionIdIn(List<Integer> values) {
            addCriterion("I_OPCION_ID in", values, "iOpcionId");
            return this;
        }

        public Criteria andIOpcionIdNotIn(List<Integer> values) {
            addCriterion("I_OPCION_ID not in", values, "iOpcionId");
            return this;
        }

        public Criteria andIOpcionIdBetween(Integer value1, Integer value2) {
            addCriterion("I_OPCION_ID between", value1, value2, "iOpcionId");
            return this;
        }

        public Criteria andIOpcionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("I_OPCION_ID not between", value1, value2, "iOpcionId");
            return this;
        }

        public Criteria andVOpcionNombreIsNull() {
            addCriterion("V_OPCION_NOMBRE is null");
            return this;
        }

        public Criteria andVOpcionNombreIsNotNull() {
            addCriterion("V_OPCION_NOMBRE is not null");
            return this;
        }

        public Criteria andVOpcionNombreEqualTo(String value) {
            addCriterion("V_OPCION_NOMBRE =", value, "vOpcionNombre");
            return this;
        }

        public Criteria andVOpcionNombreNotEqualTo(String value) {
            addCriterion("V_OPCION_NOMBRE <>", value, "vOpcionNombre");
            return this;
        }

        public Criteria andVOpcionNombreGreaterThan(String value) {
            addCriterion("V_OPCION_NOMBRE >", value, "vOpcionNombre");
            return this;
        }

        public Criteria andVOpcionNombreGreaterThanOrEqualTo(String value) {
            addCriterion("V_OPCION_NOMBRE >=", value, "vOpcionNombre");
            return this;
        }

        public Criteria andVOpcionNombreLessThan(String value) {
            addCriterion("V_OPCION_NOMBRE <", value, "vOpcionNombre");
            return this;
        }

        public Criteria andVOpcionNombreLessThanOrEqualTo(String value) {
            addCriterion("V_OPCION_NOMBRE <=", value, "vOpcionNombre");
            return this;
        }

        public Criteria andVOpcionNombreLike(String value) {
            addCriterion("V_OPCION_NOMBRE like", value, "vOpcionNombre");
            return this;
        }

        public Criteria andVOpcionNombreNotLike(String value) {
            addCriterion("V_OPCION_NOMBRE not like", value, "vOpcionNombre");
            return this;
        }

        public Criteria andVOpcionNombreIn(List<String> values) {
            addCriterion("V_OPCION_NOMBRE in", values, "vOpcionNombre");
            return this;
        }

        public Criteria andVOpcionNombreNotIn(List<String> values) {
            addCriterion("V_OPCION_NOMBRE not in", values, "vOpcionNombre");
            return this;
        }

        public Criteria andVOpcionNombreBetween(String value1, String value2) {
            addCriterion("V_OPCION_NOMBRE between", value1, value2, "vOpcionNombre");
            return this;
        }

        public Criteria andVOpcionNombreNotBetween(String value1, String value2) {
            addCriterion("V_OPCION_NOMBRE not between", value1, value2, "vOpcionNombre");
            return this;
        }

        public Criteria andVOpcionActionIsNull() {
            addCriterion("V_OPCION_ACTION is null");
            return this;
        }

        public Criteria andVOpcionActionIsNotNull() {
            addCriterion("V_OPCION_ACTION is not null");
            return this;
        }

        public Criteria andVOpcionActionEqualTo(String value) {
            addCriterion("V_OPCION_ACTION =", value, "vOpcionAction");
            return this;
        }

        public Criteria andVOpcionActionNotEqualTo(String value) {
            addCriterion("V_OPCION_ACTION <>", value, "vOpcionAction");
            return this;
        }

        public Criteria andVOpcionActionGreaterThan(String value) {
            addCriterion("V_OPCION_ACTION >", value, "vOpcionAction");
            return this;
        }

        public Criteria andVOpcionActionGreaterThanOrEqualTo(String value) {
            addCriterion("V_OPCION_ACTION >=", value, "vOpcionAction");
            return this;
        }

        public Criteria andVOpcionActionLessThan(String value) {
            addCriterion("V_OPCION_ACTION <", value, "vOpcionAction");
            return this;
        }

        public Criteria andVOpcionActionLessThanOrEqualTo(String value) {
            addCriterion("V_OPCION_ACTION <=", value, "vOpcionAction");
            return this;
        }

        public Criteria andVOpcionActionLike(String value) {
            addCriterion("V_OPCION_ACTION like", value, "vOpcionAction");
            return this;
        }

        public Criteria andVOpcionActionNotLike(String value) {
            addCriterion("V_OPCION_ACTION not like", value, "vOpcionAction");
            return this;
        }

        public Criteria andVOpcionActionIn(List<String> values) {
            addCriterion("V_OPCION_ACTION in", values, "vOpcionAction");
            return this;
        }

        public Criteria andVOpcionActionNotIn(List<String> values) {
            addCriterion("V_OPCION_ACTION not in", values, "vOpcionAction");
            return this;
        }

        public Criteria andVOpcionActionBetween(String value1, String value2) {
            addCriterion("V_OPCION_ACTION between", value1, value2, "vOpcionAction");
            return this;
        }

        public Criteria andVOpcionActionNotBetween(String value1, String value2) {
            addCriterion("V_OPCION_ACTION not between", value1, value2, "vOpcionAction");
            return this;
        }

        public Criteria andIOpcionIndpadreIsNull() {
            addCriterion("I_OPCION_INDPADRE is null");
            return this;
        }

        public Criteria andIOpcionIndpadreIsNotNull() {
            addCriterion("I_OPCION_INDPADRE is not null");
            return this;
        }

        public Criteria andIOpcionIndpadreEqualTo(Integer value) {
            addCriterion("I_OPCION_INDPADRE =", value, "iOpcionIndpadre");
            return this;
        }

        public Criteria andIOpcionIndpadreNotEqualTo(Integer value) {
            addCriterion("I_OPCION_INDPADRE <>", value, "iOpcionIndpadre");
            return this;
        }

        public Criteria andIOpcionIndpadreGreaterThan(Integer value) {
            addCriterion("I_OPCION_INDPADRE >", value, "iOpcionIndpadre");
            return this;
        }

        public Criteria andIOpcionIndpadreGreaterThanOrEqualTo(Integer value) {
            addCriterion("I_OPCION_INDPADRE >=", value, "iOpcionIndpadre");
            return this;
        }

        public Criteria andIOpcionIndpadreLessThan(Integer value) {
            addCriterion("I_OPCION_INDPADRE <", value, "iOpcionIndpadre");
            return this;
        }

        public Criteria andIOpcionIndpadreLessThanOrEqualTo(Integer value) {
            addCriterion("I_OPCION_INDPADRE <=", value, "iOpcionIndpadre");
            return this;
        }

        public Criteria andIOpcionIndpadreIn(List<Integer> values) {
            addCriterion("I_OPCION_INDPADRE in", values, "iOpcionIndpadre");
            return this;
        }

        public Criteria andIOpcionIndpadreNotIn(List<Integer> values) {
            addCriterion("I_OPCION_INDPADRE not in", values, "iOpcionIndpadre");
            return this;
        }

        public Criteria andIOpcionIndpadreBetween(Integer value1, Integer value2) {
            addCriterion("I_OPCION_INDPADRE between", value1, value2, "iOpcionIndpadre");
            return this;
        }

        public Criteria andIOpcionIndpadreNotBetween(Integer value1, Integer value2) {
            addCriterion("I_OPCION_INDPADRE not between", value1, value2, "iOpcionIndpadre");
            return this;
        }

        public Criteria andIOpcionModuloIsNull() {
            addCriterion("I_OPCION_MODULO is null");
            return this;
        }

        public Criteria andIOpcionModuloIsNotNull() {
            addCriterion("I_OPCION_MODULO is not null");
            return this;
        }

        public Criteria andIOpcionModuloEqualTo(Integer value) {
            addCriterion("I_OPCION_MODULO =", value, "iOpcionModulo");
            return this;
        }

        public Criteria andIOpcionModuloNotEqualTo(Integer value) {
            addCriterion("I_OPCION_MODULO <>", value, "iOpcionModulo");
            return this;
        }

        public Criteria andIOpcionModuloGreaterThan(Integer value) {
            addCriterion("I_OPCION_MODULO >", value, "iOpcionModulo");
            return this;
        }

        public Criteria andIOpcionModuloGreaterThanOrEqualTo(Integer value) {
            addCriterion("I_OPCION_MODULO >=", value, "iOpcionModulo");
            return this;
        }

        public Criteria andIOpcionModuloLessThan(Integer value) {
            addCriterion("I_OPCION_MODULO <", value, "iOpcionModulo");
            return this;
        }

        public Criteria andIOpcionModuloLessThanOrEqualTo(Integer value) {
            addCriterion("I_OPCION_MODULO <=", value, "iOpcionModulo");
            return this;
        }

        public Criteria andIOpcionModuloIn(List<Integer> values) {
            addCriterion("I_OPCION_MODULO in", values, "iOpcionModulo");
            return this;
        }

        public Criteria andIOpcionModuloNotIn(List<Integer> values) {
            addCriterion("I_OPCION_MODULO not in", values, "iOpcionModulo");
            return this;
        }

        public Criteria andIOpcionModuloBetween(Integer value1, Integer value2) {
            addCriterion("I_OPCION_MODULO between", value1, value2, "iOpcionModulo");
            return this;
        }

        public Criteria andIOpcionModuloNotBetween(Integer value1, Integer value2) {
            addCriterion("I_OPCION_MODULO not between", value1, value2, "iOpcionModulo");
            return this;
        }

        public Criteria andDOpcionFecregistraIsNull() {
            addCriterion("D_OPCION_FECREGISTRA is null");
            return this;
        }

        public Criteria andDOpcionFecregistraIsNotNull() {
            addCriterion("D_OPCION_FECREGISTRA is not null");
            return this;
        }

        public Criteria andDOpcionFecregistraEqualTo(Date value) {
            addCriterion("D_OPCION_FECREGISTRA =", value, "dOpcionFecregistra");
            return this;
        }

        public Criteria andDOpcionFecregistraNotEqualTo(Date value) {
            addCriterion("D_OPCION_FECREGISTRA <>", value, "dOpcionFecregistra");
            return this;
        }

        public Criteria andDOpcionFecregistraGreaterThan(Date value) {
            addCriterion("D_OPCION_FECREGISTRA >", value, "dOpcionFecregistra");
            return this;
        }

        public Criteria andDOpcionFecregistraGreaterThanOrEqualTo(Date value) {
            addCriterion("D_OPCION_FECREGISTRA >=", value, "dOpcionFecregistra");
            return this;
        }

        public Criteria andDOpcionFecregistraLessThan(Date value) {
            addCriterion("D_OPCION_FECREGISTRA <", value, "dOpcionFecregistra");
            return this;
        }

        public Criteria andDOpcionFecregistraLessThanOrEqualTo(Date value) {
            addCriterion("D_OPCION_FECREGISTRA <=", value, "dOpcionFecregistra");
            return this;
        }

        public Criteria andDOpcionFecregistraIn(List<Date> values) {
            addCriterion("D_OPCION_FECREGISTRA in", values, "dOpcionFecregistra");
            return this;
        }

        public Criteria andDOpcionFecregistraNotIn(List<Date> values) {
            addCriterion("D_OPCION_FECREGISTRA not in", values, "dOpcionFecregistra");
            return this;
        }

        public Criteria andDOpcionFecregistraBetween(Date value1, Date value2) {
            addCriterion("D_OPCION_FECREGISTRA between", value1, value2, "dOpcionFecregistra");
            return this;
        }

        public Criteria andDOpcionFecregistraNotBetween(Date value1, Date value2) {
            addCriterion("D_OPCION_FECREGISTRA not between", value1, value2, "dOpcionFecregistra");
            return this;
        }

        public Criteria andDOpcionFecmodificaIsNull() {
            addCriterion("D_OPCION_FECMODIFICA is null");
            return this;
        }

        public Criteria andDOpcionFecmodificaIsNotNull() {
            addCriterion("D_OPCION_FECMODIFICA is not null");
            return this;
        }

        public Criteria andDOpcionFecmodificaEqualTo(Date value) {
            addCriterion("D_OPCION_FECMODIFICA =", value, "dOpcionFecmodifica");
            return this;
        }

        public Criteria andDOpcionFecmodificaNotEqualTo(Date value) {
            addCriterion("D_OPCION_FECMODIFICA <>", value, "dOpcionFecmodifica");
            return this;
        }

        public Criteria andDOpcionFecmodificaGreaterThan(Date value) {
            addCriterion("D_OPCION_FECMODIFICA >", value, "dOpcionFecmodifica");
            return this;
        }

        public Criteria andDOpcionFecmodificaGreaterThanOrEqualTo(Date value) {
            addCriterion("D_OPCION_FECMODIFICA >=", value, "dOpcionFecmodifica");
            return this;
        }

        public Criteria andDOpcionFecmodificaLessThan(Date value) {
            addCriterion("D_OPCION_FECMODIFICA <", value, "dOpcionFecmodifica");
            return this;
        }

        public Criteria andDOpcionFecmodificaLessThanOrEqualTo(Date value) {
            addCriterion("D_OPCION_FECMODIFICA <=", value, "dOpcionFecmodifica");
            return this;
        }

        public Criteria andDOpcionFecmodificaIn(List<Date> values) {
            addCriterion("D_OPCION_FECMODIFICA in", values, "dOpcionFecmodifica");
            return this;
        }

        public Criteria andDOpcionFecmodificaNotIn(List<Date> values) {
            addCriterion("D_OPCION_FECMODIFICA not in", values, "dOpcionFecmodifica");
            return this;
        }

        public Criteria andDOpcionFecmodificaBetween(Date value1, Date value2) {
            addCriterion("D_OPCION_FECMODIFICA between", value1, value2, "dOpcionFecmodifica");
            return this;
        }

        public Criteria andDOpcionFecmodificaNotBetween(Date value1, Date value2) {
            addCriterion("D_OPCION_FECMODIFICA not between", value1, value2, "dOpcionFecmodifica");
            return this;
        }

        public Criteria andVOpcionDesusuregistraIsNull() {
            addCriterion("V_OPCION_DESUSUREGISTRA is null");
            return this;
        }

        public Criteria andVOpcionDesusuregistraIsNotNull() {
            addCriterion("V_OPCION_DESUSUREGISTRA is not null");
            return this;
        }

        public Criteria andVOpcionDesusuregistraEqualTo(String value) {
            addCriterion("V_OPCION_DESUSUREGISTRA =", value, "vOpcionDesusuregistra");
            return this;
        }

        public Criteria andVOpcionDesusuregistraNotEqualTo(String value) {
            addCriterion("V_OPCION_DESUSUREGISTRA <>", value, "vOpcionDesusuregistra");
            return this;
        }

        public Criteria andVOpcionDesusuregistraGreaterThan(String value) {
            addCriterion("V_OPCION_DESUSUREGISTRA >", value, "vOpcionDesusuregistra");
            return this;
        }

        public Criteria andVOpcionDesusuregistraGreaterThanOrEqualTo(String value) {
            addCriterion("V_OPCION_DESUSUREGISTRA >=", value, "vOpcionDesusuregistra");
            return this;
        }

        public Criteria andVOpcionDesusuregistraLessThan(String value) {
            addCriterion("V_OPCION_DESUSUREGISTRA <", value, "vOpcionDesusuregistra");
            return this;
        }

        public Criteria andVOpcionDesusuregistraLessThanOrEqualTo(String value) {
            addCriterion("V_OPCION_DESUSUREGISTRA <=", value, "vOpcionDesusuregistra");
            return this;
        }

        public Criteria andVOpcionDesusuregistraLike(String value) {
            addCriterion("V_OPCION_DESUSUREGISTRA like", value, "vOpcionDesusuregistra");
            return this;
        }

        public Criteria andVOpcionDesusuregistraNotLike(String value) {
            addCriterion("V_OPCION_DESUSUREGISTRA not like", value, "vOpcionDesusuregistra");
            return this;
        }

        public Criteria andVOpcionDesusuregistraIn(List<String> values) {
            addCriterion("V_OPCION_DESUSUREGISTRA in", values, "vOpcionDesusuregistra");
            return this;
        }

        public Criteria andVOpcionDesusuregistraNotIn(List<String> values) {
            addCriterion("V_OPCION_DESUSUREGISTRA not in", values, "vOpcionDesusuregistra");
            return this;
        }

        public Criteria andVOpcionDesusuregistraBetween(String value1, String value2) {
            addCriterion("V_OPCION_DESUSUREGISTRA between", value1, value2, "vOpcionDesusuregistra");
            return this;
        }

        public Criteria andVOpcionDesusuregistraNotBetween(String value1, String value2) {
            addCriterion("V_OPCION_DESUSUREGISTRA not between", value1, value2, "vOpcionDesusuregistra");
            return this;
        }

        public Criteria andVOpcionDesusumodificaIsNull() {
            addCriterion("V_OPCION_DESUSUMODIFICA is null");
            return this;
        }

        public Criteria andVOpcionDesusumodificaIsNotNull() {
            addCriterion("V_OPCION_DESUSUMODIFICA is not null");
            return this;
        }

        public Criteria andVOpcionDesusumodificaEqualTo(String value) {
            addCriterion("V_OPCION_DESUSUMODIFICA =", value, "vOpcionDesusumodifica");
            return this;
        }

        public Criteria andVOpcionDesusumodificaNotEqualTo(String value) {
            addCriterion("V_OPCION_DESUSUMODIFICA <>", value, "vOpcionDesusumodifica");
            return this;
        }

        public Criteria andVOpcionDesusumodificaGreaterThan(String value) {
            addCriterion("V_OPCION_DESUSUMODIFICA >", value, "vOpcionDesusumodifica");
            return this;
        }

        public Criteria andVOpcionDesusumodificaGreaterThanOrEqualTo(String value) {
            addCriterion("V_OPCION_DESUSUMODIFICA >=", value, "vOpcionDesusumodifica");
            return this;
        }

        public Criteria andVOpcionDesusumodificaLessThan(String value) {
            addCriterion("V_OPCION_DESUSUMODIFICA <", value, "vOpcionDesusumodifica");
            return this;
        }

        public Criteria andVOpcionDesusumodificaLessThanOrEqualTo(String value) {
            addCriterion("V_OPCION_DESUSUMODIFICA <=", value, "vOpcionDesusumodifica");
            return this;
        }

        public Criteria andVOpcionDesusumodificaLike(String value) {
            addCriterion("V_OPCION_DESUSUMODIFICA like", value, "vOpcionDesusumodifica");
            return this;
        }

        public Criteria andVOpcionDesusumodificaNotLike(String value) {
            addCriterion("V_OPCION_DESUSUMODIFICA not like", value, "vOpcionDesusumodifica");
            return this;
        }

        public Criteria andVOpcionDesusumodificaIn(List<String> values) {
            addCriterion("V_OPCION_DESUSUMODIFICA in", values, "vOpcionDesusumodifica");
            return this;
        }

        public Criteria andVOpcionDesusumodificaNotIn(List<String> values) {
            addCriterion("V_OPCION_DESUSUMODIFICA not in", values, "vOpcionDesusumodifica");
            return this;
        }

        public Criteria andVOpcionDesusumodificaBetween(String value1, String value2) {
            addCriterion("V_OPCION_DESUSUMODIFICA between", value1, value2, "vOpcionDesusumodifica");
            return this;
        }

        public Criteria andVOpcionDesusumodificaNotBetween(String value1, String value2) {
            addCriterion("V_OPCION_DESUSUMODIFICA not between", value1, value2, "vOpcionDesusumodifica");
            return this;
        }

        public Criteria andVOpcionDesipregistraIsNull() {
            addCriterion("V_OPCION_DESIPREGISTRA is null");
            return this;
        }

        public Criteria andVOpcionDesipregistraIsNotNull() {
            addCriterion("V_OPCION_DESIPREGISTRA is not null");
            return this;
        }

        public Criteria andVOpcionDesipregistraEqualTo(String value) {
            addCriterion("V_OPCION_DESIPREGISTRA =", value, "vOpcionDesipregistra");
            return this;
        }

        public Criteria andVOpcionDesipregistraNotEqualTo(String value) {
            addCriterion("V_OPCION_DESIPREGISTRA <>", value, "vOpcionDesipregistra");
            return this;
        }

        public Criteria andVOpcionDesipregistraGreaterThan(String value) {
            addCriterion("V_OPCION_DESIPREGISTRA >", value, "vOpcionDesipregistra");
            return this;
        }

        public Criteria andVOpcionDesipregistraGreaterThanOrEqualTo(String value) {
            addCriterion("V_OPCION_DESIPREGISTRA >=", value, "vOpcionDesipregistra");
            return this;
        }

        public Criteria andVOpcionDesipregistraLessThan(String value) {
            addCriterion("V_OPCION_DESIPREGISTRA <", value, "vOpcionDesipregistra");
            return this;
        }

        public Criteria andVOpcionDesipregistraLessThanOrEqualTo(String value) {
            addCriterion("V_OPCION_DESIPREGISTRA <=", value, "vOpcionDesipregistra");
            return this;
        }

        public Criteria andVOpcionDesipregistraLike(String value) {
            addCriterion("V_OPCION_DESIPREGISTRA like", value, "vOpcionDesipregistra");
            return this;
        }

        public Criteria andVOpcionDesipregistraNotLike(String value) {
            addCriterion("V_OPCION_DESIPREGISTRA not like", value, "vOpcionDesipregistra");
            return this;
        }

        public Criteria andVOpcionDesipregistraIn(List<String> values) {
            addCriterion("V_OPCION_DESIPREGISTRA in", values, "vOpcionDesipregistra");
            return this;
        }

        public Criteria andVOpcionDesipregistraNotIn(List<String> values) {
            addCriterion("V_OPCION_DESIPREGISTRA not in", values, "vOpcionDesipregistra");
            return this;
        }

        public Criteria andVOpcionDesipregistraBetween(String value1, String value2) {
            addCriterion("V_OPCION_DESIPREGISTRA between", value1, value2, "vOpcionDesipregistra");
            return this;
        }

        public Criteria andVOpcionDesipregistraNotBetween(String value1, String value2) {
            addCriterion("V_OPCION_DESIPREGISTRA not between", value1, value2, "vOpcionDesipregistra");
            return this;
        }

        public Criteria andVOpcionDesipmodificaIsNull() {
            addCriterion("V_OPCION_DESIPMODIFICA is null");
            return this;
        }

        public Criteria andVOpcionDesipmodificaIsNotNull() {
            addCriterion("V_OPCION_DESIPMODIFICA is not null");
            return this;
        }

        public Criteria andVOpcionDesipmodificaEqualTo(String value) {
            addCriterion("V_OPCION_DESIPMODIFICA =", value, "vOpcionDesipmodifica");
            return this;
        }

        public Criteria andVOpcionDesipmodificaNotEqualTo(String value) {
            addCriterion("V_OPCION_DESIPMODIFICA <>", value, "vOpcionDesipmodifica");
            return this;
        }

        public Criteria andVOpcionDesipmodificaGreaterThan(String value) {
            addCriterion("V_OPCION_DESIPMODIFICA >", value, "vOpcionDesipmodifica");
            return this;
        }

        public Criteria andVOpcionDesipmodificaGreaterThanOrEqualTo(String value) {
            addCriterion("V_OPCION_DESIPMODIFICA >=", value, "vOpcionDesipmodifica");
            return this;
        }

        public Criteria andVOpcionDesipmodificaLessThan(String value) {
            addCriterion("V_OPCION_DESIPMODIFICA <", value, "vOpcionDesipmodifica");
            return this;
        }

        public Criteria andVOpcionDesipmodificaLessThanOrEqualTo(String value) {
            addCriterion("V_OPCION_DESIPMODIFICA <=", value, "vOpcionDesipmodifica");
            return this;
        }

        public Criteria andVOpcionDesipmodificaLike(String value) {
            addCriterion("V_OPCION_DESIPMODIFICA like", value, "vOpcionDesipmodifica");
            return this;
        }

        public Criteria andVOpcionDesipmodificaNotLike(String value) {
            addCriterion("V_OPCION_DESIPMODIFICA not like", value, "vOpcionDesipmodifica");
            return this;
        }

        public Criteria andVOpcionDesipmodificaIn(List<String> values) {
            addCriterion("V_OPCION_DESIPMODIFICA in", values, "vOpcionDesipmodifica");
            return this;
        }

        public Criteria andVOpcionDesipmodificaNotIn(List<String> values) {
            addCriterion("V_OPCION_DESIPMODIFICA not in", values, "vOpcionDesipmodifica");
            return this;
        }

        public Criteria andVOpcionDesipmodificaBetween(String value1, String value2) {
            addCriterion("V_OPCION_DESIPMODIFICA between", value1, value2, "vOpcionDesipmodifica");
            return this;
        }

        public Criteria andVOpcionDesipmodificaNotBetween(String value1, String value2) {
            addCriterion("V_OPCION_DESIPMODIFICA not between", value1, value2, "vOpcionDesipmodifica");
            return this;
        }

        public Criteria andIOpcionEstadoIsNull() {
            addCriterion("I_OPCION_ESTADO is null");
            return this;
        }

        public Criteria andIOpcionEstadoIsNotNull() {
            addCriterion("I_OPCION_ESTADO is not null");
            return this;
        }

        public Criteria andIOpcionEstadoEqualTo(Integer value) {
            addCriterion("I_OPCION_ESTADO =", value, "iOpcionEstado");
            return this;
        }

        public Criteria andIOpcionEstadoNotEqualTo(Integer value) {
            addCriterion("I_OPCION_ESTADO <>", value, "iOpcionEstado");
            return this;
        }

        public Criteria andIOpcionEstadoGreaterThan(Integer value) {
            addCriterion("I_OPCION_ESTADO >", value, "iOpcionEstado");
            return this;
        }

        public Criteria andIOpcionEstadoGreaterThanOrEqualTo(Integer value) {
            addCriterion("I_OPCION_ESTADO >=", value, "iOpcionEstado");
            return this;
        }

        public Criteria andIOpcionEstadoLessThan(Integer value) {
            addCriterion("I_OPCION_ESTADO <", value, "iOpcionEstado");
            return this;
        }

        public Criteria andIOpcionEstadoLessThanOrEqualTo(Integer value) {
            addCriterion("I_OPCION_ESTADO <=", value, "iOpcionEstado");
            return this;
        }

        public Criteria andIOpcionEstadoIn(List<Integer> values) {
            addCriterion("I_OPCION_ESTADO in", values, "iOpcionEstado");
            return this;
        }

        public Criteria andIOpcionEstadoNotIn(List<Integer> values) {
            addCriterion("I_OPCION_ESTADO not in", values, "iOpcionEstado");
            return this;
        }

        public Criteria andIOpcionEstadoBetween(Integer value1, Integer value2) {
            addCriterion("I_OPCION_ESTADO between", value1, value2, "iOpcionEstado");
            return this;
        }

        public Criteria andIOpcionEstadoNotBetween(Integer value1, Integer value2) {
            addCriterion("I_OPCION_ESTADO not between", value1, value2, "iOpcionEstado");
            return this;
        }
    }
}