package pe.gob.ep.ginnet.seguridad.bean;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class UsuarioRolCriteria {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table ctrl_seg_usuarioxrol
     *
     * @ibatorgenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table ctrl_seg_usuarioxrol
     *
     * @ibatorgenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuarioxrol
     *
     * @ibatorgenerated
     */
    public UsuarioRolCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuarioxrol
     *
     * @ibatorgenerated
     */
    protected UsuarioRolCriteria(UsuarioRolCriteria example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuarioxrol
     *
     * @ibatorgenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuarioxrol
     *
     * @ibatorgenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuarioxrol
     *
     * @ibatorgenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuarioxrol
     *
     * @ibatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuarioxrol
     *
     * @ibatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuarioxrol
     *
     * @ibatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuarioxrol
     *
     * @ibatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table ctrl_seg_usuarioxrol
     *
     * @ibatorgenerated
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIUsuarioxrolIdIsNull() {
            addCriterion("I_USUARIOXROL_ID is null");
            return this;
        }

        public Criteria andIUsuarioxrolIdIsNotNull() {
            addCriterion("I_USUARIOXROL_ID is not null");
            return this;
        }

        public Criteria andIUsuarioxrolIdEqualTo(Integer value) {
            addCriterion("I_USUARIOXROL_ID =", value, "iUsuarioxrolId");
            return this;
        }

        public Criteria andIUsuarioxrolIdNotEqualTo(Integer value) {
            addCriterion("I_USUARIOXROL_ID <>", value, "iUsuarioxrolId");
            return this;
        }

        public Criteria andIUsuarioxrolIdGreaterThan(Integer value) {
            addCriterion("I_USUARIOXROL_ID >", value, "iUsuarioxrolId");
            return this;
        }

        public Criteria andIUsuarioxrolIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("I_USUARIOXROL_ID >=", value, "iUsuarioxrolId");
            return this;
        }

        public Criteria andIUsuarioxrolIdLessThan(Integer value) {
            addCriterion("I_USUARIOXROL_ID <", value, "iUsuarioxrolId");
            return this;
        }

        public Criteria andIUsuarioxrolIdLessThanOrEqualTo(Integer value) {
            addCriterion("I_USUARIOXROL_ID <=", value, "iUsuarioxrolId");
            return this;
        }

        public Criteria andIUsuarioxrolIdIn(List<Integer> values) {
            addCriterion("I_USUARIOXROL_ID in", values, "iUsuarioxrolId");
            return this;
        }

        public Criteria andIUsuarioxrolIdNotIn(List<Integer> values) {
            addCriterion("I_USUARIOXROL_ID not in", values, "iUsuarioxrolId");
            return this;
        }

        public Criteria andIUsuarioxrolIdBetween(Integer value1, Integer value2) {
            addCriterion("I_USUARIOXROL_ID between", value1, value2, "iUsuarioxrolId");
            return this;
        }

        public Criteria andIUsuarioxrolIdNotBetween(Integer value1, Integer value2) {
            addCriterion("I_USUARIOXROL_ID not between", value1, value2, "iUsuarioxrolId");
            return this;
        }

        public Criteria andIUsuarioxrolUsuarioIdIsNull() {
            addCriterion("I_USUARIOXROL_USUARIO_ID is null");
            return this;
        }

        public Criteria andIUsuarioxrolUsuarioIdIsNotNull() {
            addCriterion("I_USUARIOXROL_USUARIO_ID is not null");
            return this;
        }

        public Criteria andIUsuarioxrolUsuarioIdEqualTo(Integer value) {
            addCriterion("I_USUARIOXROL_USUARIO_ID =", value, "iUsuarioxrolUsuarioId");
            return this;
        }

        public Criteria andIUsuarioxrolUsuarioIdNotEqualTo(Integer value) {
            addCriterion("I_USUARIOXROL_USUARIO_ID <>", value, "iUsuarioxrolUsuarioId");
            return this;
        }

        public Criteria andIUsuarioxrolUsuarioIdGreaterThan(Integer value) {
            addCriterion("I_USUARIOXROL_USUARIO_ID >", value, "iUsuarioxrolUsuarioId");
            return this;
        }

        public Criteria andIUsuarioxrolUsuarioIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("I_USUARIOXROL_USUARIO_ID >=", value, "iUsuarioxrolUsuarioId");
            return this;
        }

        public Criteria andIUsuarioxrolUsuarioIdLessThan(Integer value) {
            addCriterion("I_USUARIOXROL_USUARIO_ID <", value, "iUsuarioxrolUsuarioId");
            return this;
        }

        public Criteria andIUsuarioxrolUsuarioIdLessThanOrEqualTo(Integer value) {
            addCriterion("I_USUARIOXROL_USUARIO_ID <=", value, "iUsuarioxrolUsuarioId");
            return this;
        }

        public Criteria andIUsuarioxrolUsuarioIdIn(List<Integer> values) {
            addCriterion("I_USUARIOXROL_USUARIO_ID in", values, "iUsuarioxrolUsuarioId");
            return this;
        }

        public Criteria andIUsuarioxrolUsuarioIdNotIn(List<Integer> values) {
            addCriterion("I_USUARIOXROL_USUARIO_ID not in", values, "iUsuarioxrolUsuarioId");
            return this;
        }

        public Criteria andIUsuarioxrolUsuarioIdBetween(Integer value1, Integer value2) {
            addCriterion("I_USUARIOXROL_USUARIO_ID between", value1, value2, "iUsuarioxrolUsuarioId");
            return this;
        }

        public Criteria andIUsuarioxrolUsuarioIdNotBetween(Integer value1, Integer value2) {
            addCriterion("I_USUARIOXROL_USUARIO_ID not between", value1, value2, "iUsuarioxrolUsuarioId");
            return this;
        }

        public Criteria andIUsuarioxrolRolIdIsNull() {
            addCriterion("I_USUARIOXROL_ROL_ID is null");
            return this;
        }

        public Criteria andIUsuarioxrolRolIdIsNotNull() {
            addCriterion("I_USUARIOXROL_ROL_ID is not null");
            return this;
        }

        public Criteria andIUsuarioxrolRolIdEqualTo(Integer value) {
            addCriterion("I_USUARIOXROL_ROL_ID =", value, "iUsuarioxrolRolId");
            return this;
        }

        public Criteria andIUsuarioxrolRolIdNotEqualTo(Integer value) {
            addCriterion("I_USUARIOXROL_ROL_ID <>", value, "iUsuarioxrolRolId");
            return this;
        }

        public Criteria andIUsuarioxrolRolIdGreaterThan(Integer value) {
            addCriterion("I_USUARIOXROL_ROL_ID >", value, "iUsuarioxrolRolId");
            return this;
        }

        public Criteria andIUsuarioxrolRolIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("I_USUARIOXROL_ROL_ID >=", value, "iUsuarioxrolRolId");
            return this;
        }

        public Criteria andIUsuarioxrolRolIdLessThan(Integer value) {
            addCriterion("I_USUARIOXROL_ROL_ID <", value, "iUsuarioxrolRolId");
            return this;
        }

        public Criteria andIUsuarioxrolRolIdLessThanOrEqualTo(Integer value) {
            addCriterion("I_USUARIOXROL_ROL_ID <=", value, "iUsuarioxrolRolId");
            return this;
        }

        public Criteria andIUsuarioxrolRolIdIn(List<Integer> values) {
            addCriterion("I_USUARIOXROL_ROL_ID in", values, "iUsuarioxrolRolId");
            return this;
        }

        public Criteria andIUsuarioxrolRolIdNotIn(List<Integer> values) {
            addCriterion("I_USUARIOXROL_ROL_ID not in", values, "iUsuarioxrolRolId");
            return this;
        }

        public Criteria andIUsuarioxrolRolIdBetween(Integer value1, Integer value2) {
            addCriterion("I_USUARIOXROL_ROL_ID between", value1, value2, "iUsuarioxrolRolId");
            return this;
        }

        public Criteria andIUsuarioxrolRolIdNotBetween(Integer value1, Integer value2) {
            addCriterion("I_USUARIOXROL_ROL_ID not between", value1, value2, "iUsuarioxrolRolId");
            return this;
        }
    }
}