package pe.gob.ep.ginnet.seguridad.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class UsuarioCriteria {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table ctrl_seg_usuario
     *
     * @ibatorgenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table ctrl_seg_usuario
     *
     * @ibatorgenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuario
     *
     * @ibatorgenerated
     */
    public UsuarioCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuario
     *
     * @ibatorgenerated
     */
    protected UsuarioCriteria(UsuarioCriteria example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuario
     *
     * @ibatorgenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuario
     *
     * @ibatorgenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuario
     *
     * @ibatorgenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuario
     *
     * @ibatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuario
     *
     * @ibatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuario
     *
     * @ibatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ctrl_seg_usuario
     *
     * @ibatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table ctrl_seg_usuario
     *
     * @ibatorgenerated
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIUsuarioIdIsNull() {
            addCriterion("I_USUARIO_ID is null");
            return this;
        }

        public Criteria andIUsuarioIdIsNotNull() {
            addCriterion("I_USUARIO_ID is not null");
            return this;
        }

        public Criteria andIUsuarioIdEqualTo(Integer value) {
            addCriterion("I_USUARIO_ID =", value, "iUsuarioId");
            return this;
        }

        public Criteria andIUsuarioIdNotEqualTo(Integer value) {
            addCriterion("I_USUARIO_ID <>", value, "iUsuarioId");
            return this;
        }

        public Criteria andIUsuarioIdGreaterThan(Integer value) {
            addCriterion("I_USUARIO_ID >", value, "iUsuarioId");
            return this;
        }

        public Criteria andIUsuarioIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("I_USUARIO_ID >=", value, "iUsuarioId");
            return this;
        }

        public Criteria andIUsuarioIdLessThan(Integer value) {
            addCriterion("I_USUARIO_ID <", value, "iUsuarioId");
            return this;
        }

        public Criteria andIUsuarioIdLessThanOrEqualTo(Integer value) {
            addCriterion("I_USUARIO_ID <=", value, "iUsuarioId");
            return this;
        }

        public Criteria andIUsuarioIdIn(List<Integer> values) {
            addCriterion("I_USUARIO_ID in", values, "iUsuarioId");
            return this;
        }

        public Criteria andIUsuarioIdNotIn(List<Integer> values) {
            addCriterion("I_USUARIO_ID not in", values, "iUsuarioId");
            return this;
        }

        public Criteria andIUsuarioIdBetween(Integer value1, Integer value2) {
            addCriterion("I_USUARIO_ID between", value1, value2, "iUsuarioId");
            return this;
        }

        public Criteria andIUsuarioIdNotBetween(Integer value1, Integer value2) {
            addCriterion("I_USUARIO_ID not between", value1, value2, "iUsuarioId");
            return this;
        }

        public Criteria andVUsuarioUsernameIsNull() {
            addCriterion("V_USUARIO_USERNAME is null");
            return this;
        }

        public Criteria andVUsuarioUsernameIsNotNull() {
            addCriterion("V_USUARIO_USERNAME is not null");
            return this;
        }

        public Criteria andVUsuarioUsernameEqualTo(String value) {
            addCriterion("V_USUARIO_USERNAME =", value, "vUsuarioUsername");
            return this;
        }

        public Criteria andVUsuarioUsernameNotEqualTo(String value) {
            addCriterion("V_USUARIO_USERNAME <>", value, "vUsuarioUsername");
            return this;
        }

        public Criteria andVUsuarioUsernameGreaterThan(String value) {
            addCriterion("V_USUARIO_USERNAME >", value, "vUsuarioUsername");
            return this;
        }

        public Criteria andVUsuarioUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("V_USUARIO_USERNAME >=", value, "vUsuarioUsername");
            return this;
        }

        public Criteria andVUsuarioUsernameLessThan(String value) {
            addCriterion("V_USUARIO_USERNAME <", value, "vUsuarioUsername");
            return this;
        }

        public Criteria andVUsuarioUsernameLessThanOrEqualTo(String value) {
            addCriterion("V_USUARIO_USERNAME <=", value, "vUsuarioUsername");
            return this;
        }

        public Criteria andVUsuarioUsernameLike(String value) {
            addCriterion("V_USUARIO_USERNAME like", value, "vUsuarioUsername");
            return this;
        }

        public Criteria andVUsuarioUsernameNotLike(String value) {
            addCriterion("V_USUARIO_USERNAME not like", value, "vUsuarioUsername");
            return this;
        }

        public Criteria andVUsuarioUsernameIn(List<String> values) {
            addCriterion("V_USUARIO_USERNAME in", values, "vUsuarioUsername");
            return this;
        }

        public Criteria andVUsuarioUsernameNotIn(List<String> values) {
            addCriterion("V_USUARIO_USERNAME not in", values, "vUsuarioUsername");
            return this;
        }

        public Criteria andVUsuarioUsernameBetween(String value1, String value2) {
            addCriterion("V_USUARIO_USERNAME between", value1, value2, "vUsuarioUsername");
            return this;
        }

        public Criteria andVUsuarioUsernameNotBetween(String value1, String value2) {
            addCriterion("V_USUARIO_USERNAME not between", value1, value2, "vUsuarioUsername");
            return this;
        }

        public Criteria andVUsuarioPasswordIsNull() {
            addCriterion("V_USUARIO_PASSWORD is null");
            return this;
        }

        public Criteria andVUsuarioPasswordIsNotNull() {
            addCriterion("V_USUARIO_PASSWORD is not null");
            return this;
        }

        public Criteria andVUsuarioPasswordEqualTo(String value) {
            addCriterion("V_USUARIO_PASSWORD =", value, "vUsuarioPassword");
            return this;
        }

        public Criteria andVUsuarioPasswordNotEqualTo(String value) {
            addCriterion("V_USUARIO_PASSWORD <>", value, "vUsuarioPassword");
            return this;
        }

        public Criteria andVUsuarioPasswordGreaterThan(String value) {
            addCriterion("V_USUARIO_PASSWORD >", value, "vUsuarioPassword");
            return this;
        }

        public Criteria andVUsuarioPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("V_USUARIO_PASSWORD >=", value, "vUsuarioPassword");
            return this;
        }

        public Criteria andVUsuarioPasswordLessThan(String value) {
            addCriterion("V_USUARIO_PASSWORD <", value, "vUsuarioPassword");
            return this;
        }

        public Criteria andVUsuarioPasswordLessThanOrEqualTo(String value) {
            addCriterion("V_USUARIO_PASSWORD <=", value, "vUsuarioPassword");
            return this;
        }

        public Criteria andVUsuarioPasswordLike(String value) {
            addCriterion("V_USUARIO_PASSWORD like", value, "vUsuarioPassword");
            return this;
        }

        public Criteria andVUsuarioPasswordNotLike(String value) {
            addCriterion("V_USUARIO_PASSWORD not like", value, "vUsuarioPassword");
            return this;
        }

        public Criteria andVUsuarioPasswordIn(List<String> values) {
            addCriterion("V_USUARIO_PASSWORD in", values, "vUsuarioPassword");
            return this;
        }

        public Criteria andVUsuarioPasswordNotIn(List<String> values) {
            addCriterion("V_USUARIO_PASSWORD not in", values, "vUsuarioPassword");
            return this;
        }

        public Criteria andVUsuarioPasswordBetween(String value1, String value2) {
            addCriterion("V_USUARIO_PASSWORD between", value1, value2, "vUsuarioPassword");
            return this;
        }

        public Criteria andVUsuarioPasswordNotBetween(String value1, String value2) {
            addCriterion("V_USUARIO_PASSWORD not between", value1, value2, "vUsuarioPassword");
            return this;
        }

        public Criteria andVUsuarioApPaternoIsNull() {
            addCriterion("V_USUARIO_AP_PATERNO is null");
            return this;
        }

        public Criteria andVUsuarioApPaternoIsNotNull() {
            addCriterion("V_USUARIO_AP_PATERNO is not null");
            return this;
        }

        public Criteria andVUsuarioApPaternoEqualTo(String value) {
            addCriterion("V_USUARIO_AP_PATERNO =", value, "vUsuarioApPaterno");
            return this;
        }

        public Criteria andVUsuarioApPaternoNotEqualTo(String value) {
            addCriterion("V_USUARIO_AP_PATERNO <>", value, "vUsuarioApPaterno");
            return this;
        }

        public Criteria andVUsuarioApPaternoGreaterThan(String value) {
            addCriterion("V_USUARIO_AP_PATERNO >", value, "vUsuarioApPaterno");
            return this;
        }

        public Criteria andVUsuarioApPaternoGreaterThanOrEqualTo(String value) {
            addCriterion("V_USUARIO_AP_PATERNO >=", value, "vUsuarioApPaterno");
            return this;
        }

        public Criteria andVUsuarioApPaternoLessThan(String value) {
            addCriterion("V_USUARIO_AP_PATERNO <", value, "vUsuarioApPaterno");
            return this;
        }

        public Criteria andVUsuarioApPaternoLessThanOrEqualTo(String value) {
            addCriterion("V_USUARIO_AP_PATERNO <=", value, "vUsuarioApPaterno");
            return this;
        }

        public Criteria andVUsuarioApPaternoLike(String value) {
            addCriterion("V_USUARIO_AP_PATERNO like", value, "vUsuarioApPaterno");
            return this;
        }

        public Criteria andVUsuarioApPaternoNotLike(String value) {
            addCriterion("V_USUARIO_AP_PATERNO not like", value, "vUsuarioApPaterno");
            return this;
        }

        public Criteria andVUsuarioApPaternoIn(List<String> values) {
            addCriterion("V_USUARIO_AP_PATERNO in", values, "vUsuarioApPaterno");
            return this;
        }

        public Criteria andVUsuarioApPaternoNotIn(List<String> values) {
            addCriterion("V_USUARIO_AP_PATERNO not in", values, "vUsuarioApPaterno");
            return this;
        }

        public Criteria andVUsuarioApPaternoBetween(String value1, String value2) {
            addCriterion("V_USUARIO_AP_PATERNO between", value1, value2, "vUsuarioApPaterno");
            return this;
        }

        public Criteria andVUsuarioApPaternoNotBetween(String value1, String value2) {
            addCriterion("V_USUARIO_AP_PATERNO not between", value1, value2, "vUsuarioApPaterno");
            return this;
        }

        public Criteria andVUsuarioApMaternoIsNull() {
            addCriterion("V_USUARIO_AP_MATERNO is null");
            return this;
        }

        public Criteria andVUsuarioApMaternoIsNotNull() {
            addCriterion("V_USUARIO_AP_MATERNO is not null");
            return this;
        }

        public Criteria andVUsuarioApMaternoEqualTo(String value) {
            addCriterion("V_USUARIO_AP_MATERNO =", value, "vUsuarioApMaterno");
            return this;
        }

        public Criteria andVUsuarioApMaternoNotEqualTo(String value) {
            addCriterion("V_USUARIO_AP_MATERNO <>", value, "vUsuarioApMaterno");
            return this;
        }

        public Criteria andVUsuarioApMaternoGreaterThan(String value) {
            addCriterion("V_USUARIO_AP_MATERNO >", value, "vUsuarioApMaterno");
            return this;
        }

        public Criteria andVUsuarioApMaternoGreaterThanOrEqualTo(String value) {
            addCriterion("V_USUARIO_AP_MATERNO >=", value, "vUsuarioApMaterno");
            return this;
        }

        public Criteria andVUsuarioApMaternoLessThan(String value) {
            addCriterion("V_USUARIO_AP_MATERNO <", value, "vUsuarioApMaterno");
            return this;
        }

        public Criteria andVUsuarioApMaternoLessThanOrEqualTo(String value) {
            addCriterion("V_USUARIO_AP_MATERNO <=", value, "vUsuarioApMaterno");
            return this;
        }

        public Criteria andVUsuarioApMaternoLike(String value) {
            addCriterion("V_USUARIO_AP_MATERNO like", value, "vUsuarioApMaterno");
            return this;
        }

        public Criteria andVUsuarioApMaternoNotLike(String value) {
            addCriterion("V_USUARIO_AP_MATERNO not like", value, "vUsuarioApMaterno");
            return this;
        }

        public Criteria andVUsuarioApMaternoIn(List<String> values) {
            addCriterion("V_USUARIO_AP_MATERNO in", values, "vUsuarioApMaterno");
            return this;
        }

        public Criteria andVUsuarioApMaternoNotIn(List<String> values) {
            addCriterion("V_USUARIO_AP_MATERNO not in", values, "vUsuarioApMaterno");
            return this;
        }

        public Criteria andVUsuarioApMaternoBetween(String value1, String value2) {
            addCriterion("V_USUARIO_AP_MATERNO between", value1, value2, "vUsuarioApMaterno");
            return this;
        }

        public Criteria andVUsuarioApMaternoNotBetween(String value1, String value2) {
            addCriterion("V_USUARIO_AP_MATERNO not between", value1, value2, "vUsuarioApMaterno");
            return this;
        }

        public Criteria andVUsuarioNombresIsNull() {
            addCriterion("V_USUARIO_NOMBRES is null");
            return this;
        }

        public Criteria andVUsuarioNombresIsNotNull() {
            addCriterion("V_USUARIO_NOMBRES is not null");
            return this;
        }

        public Criteria andVUsuarioNombresEqualTo(String value) {
            addCriterion("V_USUARIO_NOMBRES =", value, "vUsuarioNombres");
            return this;
        }

        public Criteria andVUsuarioNombresNotEqualTo(String value) {
            addCriterion("V_USUARIO_NOMBRES <>", value, "vUsuarioNombres");
            return this;
        }

        public Criteria andVUsuarioNombresGreaterThan(String value) {
            addCriterion("V_USUARIO_NOMBRES >", value, "vUsuarioNombres");
            return this;
        }

        public Criteria andVUsuarioNombresGreaterThanOrEqualTo(String value) {
            addCriterion("V_USUARIO_NOMBRES >=", value, "vUsuarioNombres");
            return this;
        }

        public Criteria andVUsuarioNombresLessThan(String value) {
            addCriterion("V_USUARIO_NOMBRES <", value, "vUsuarioNombres");
            return this;
        }

        public Criteria andVUsuarioNombresLessThanOrEqualTo(String value) {
            addCriterion("V_USUARIO_NOMBRES <=", value, "vUsuarioNombres");
            return this;
        }

        public Criteria andVUsuarioNombresLike(String value) {
            addCriterion("V_USUARIO_NOMBRES like", value, "vUsuarioNombres");
            return this;
        }

        public Criteria andVUsuarioNombresNotLike(String value) {
            addCriterion("V_USUARIO_NOMBRES not like", value, "vUsuarioNombres");
            return this;
        }

        public Criteria andVUsuarioNombresIn(List<String> values) {
            addCriterion("V_USUARIO_NOMBRES in", values, "vUsuarioNombres");
            return this;
        }

        public Criteria andVUsuarioNombresNotIn(List<String> values) {
            addCriterion("V_USUARIO_NOMBRES not in", values, "vUsuarioNombres");
            return this;
        }

        public Criteria andVUsuarioNombresBetween(String value1, String value2) {
            addCriterion("V_USUARIO_NOMBRES between", value1, value2, "vUsuarioNombres");
            return this;
        }

        public Criteria andVUsuarioNombresNotBetween(String value1, String value2) {
            addCriterion("V_USUARIO_NOMBRES not between", value1, value2, "vUsuarioNombres");
            return this;
        }

        public Criteria andCUsuarioCodCargoIsNull() {
            addCriterion("C_USUARIO_COD_CARGO is null");
            return this;
        }

        public Criteria andCUsuarioCodCargoIsNotNull() {
            addCriterion("C_USUARIO_COD_CARGO is not null");
            return this;
        }

        public Criteria andCUsuarioCodCargoEqualTo(String value) {
            addCriterion("C_USUARIO_COD_CARGO =", value, "cUsuarioCodCargo");
            return this;
        }

        public Criteria andCUsuarioCodCargoNotEqualTo(String value) {
            addCriterion("C_USUARIO_COD_CARGO <>", value, "cUsuarioCodCargo");
            return this;
        }

        public Criteria andCUsuarioCodCargoGreaterThan(String value) {
            addCriterion("C_USUARIO_COD_CARGO >", value, "cUsuarioCodCargo");
            return this;
        }

        public Criteria andCUsuarioCodCargoGreaterThanOrEqualTo(String value) {
            addCriterion("C_USUARIO_COD_CARGO >=", value, "cUsuarioCodCargo");
            return this;
        }

        public Criteria andCUsuarioCodCargoLessThan(String value) {
            addCriterion("C_USUARIO_COD_CARGO <", value, "cUsuarioCodCargo");
            return this;
        }

        public Criteria andCUsuarioCodCargoLessThanOrEqualTo(String value) {
            addCriterion("C_USUARIO_COD_CARGO <=", value, "cUsuarioCodCargo");
            return this;
        }

        public Criteria andCUsuarioCodCargoLike(String value) {
            addCriterion("C_USUARIO_COD_CARGO like", value, "cUsuarioCodCargo");
            return this;
        }

        public Criteria andCUsuarioCodCargoNotLike(String value) {
            addCriterion("C_USUARIO_COD_CARGO not like", value, "cUsuarioCodCargo");
            return this;
        }

        public Criteria andCUsuarioCodCargoIn(List<String> values) {
            addCriterion("C_USUARIO_COD_CARGO in", values, "cUsuarioCodCargo");
            return this;
        }

        public Criteria andCUsuarioCodCargoNotIn(List<String> values) {
            addCriterion("C_USUARIO_COD_CARGO not in", values, "cUsuarioCodCargo");
            return this;
        }

        public Criteria andCUsuarioCodCargoBetween(String value1, String value2) {
            addCriterion("C_USUARIO_COD_CARGO between", value1, value2, "cUsuarioCodCargo");
            return this;
        }

        public Criteria andCUsuarioCodCargoNotBetween(String value1, String value2) {
            addCriterion("C_USUARIO_COD_CARGO not between", value1, value2, "cUsuarioCodCargo");
            return this;
        }

        public Criteria andCUsuarioCodGradoIsNull() {
            addCriterion("C_USUARIO_COD_GRADO is null");
            return this;
        }

        public Criteria andCUsuarioCodGradoIsNotNull() {
            addCriterion("C_USUARIO_COD_GRADO is not null");
            return this;
        }

        public Criteria andCUsuarioCodGradoEqualTo(String value) {
            addCriterion("C_USUARIO_COD_GRADO =", value, "cUsuarioCodGrado");
            return this;
        }

        public Criteria andCUsuarioCodGradoNotEqualTo(String value) {
            addCriterion("C_USUARIO_COD_GRADO <>", value, "cUsuarioCodGrado");
            return this;
        }

        public Criteria andCUsuarioCodGradoGreaterThan(String value) {
            addCriterion("C_USUARIO_COD_GRADO >", value, "cUsuarioCodGrado");
            return this;
        }

        public Criteria andCUsuarioCodGradoGreaterThanOrEqualTo(String value) {
            addCriterion("C_USUARIO_COD_GRADO >=", value, "cUsuarioCodGrado");
            return this;
        }

        public Criteria andCUsuarioCodGradoLessThan(String value) {
            addCriterion("C_USUARIO_COD_GRADO <", value, "cUsuarioCodGrado");
            return this;
        }

        public Criteria andCUsuarioCodGradoLessThanOrEqualTo(String value) {
            addCriterion("C_USUARIO_COD_GRADO <=", value, "cUsuarioCodGrado");
            return this;
        }

        public Criteria andCUsuarioCodGradoLike(String value) {
            addCriterion("C_USUARIO_COD_GRADO like", value, "cUsuarioCodGrado");
            return this;
        }

        public Criteria andCUsuarioCodGradoNotLike(String value) {
            addCriterion("C_USUARIO_COD_GRADO not like", value, "cUsuarioCodGrado");
            return this;
        }

        public Criteria andCUsuarioCodGradoIn(List<String> values) {
            addCriterion("C_USUARIO_COD_GRADO in", values, "cUsuarioCodGrado");
            return this;
        }

        public Criteria andCUsuarioCodGradoNotIn(List<String> values) {
            addCriterion("C_USUARIO_COD_GRADO not in", values, "cUsuarioCodGrado");
            return this;
        }

        public Criteria andCUsuarioCodGradoBetween(String value1, String value2) {
            addCriterion("C_USUARIO_COD_GRADO between", value1, value2, "cUsuarioCodGrado");
            return this;
        }

        public Criteria andCUsuarioCodGradoNotBetween(String value1, String value2) {
            addCriterion("C_USUARIO_COD_GRADO not between", value1, value2, "cUsuarioCodGrado");
            return this;
        }

        public Criteria andDUsuarioFecregistraIsNull() {
            addCriterion("D_USUARIO_FECREGISTRA is null");
            return this;
        }

        public Criteria andDUsuarioFecregistraIsNotNull() {
            addCriterion("D_USUARIO_FECREGISTRA is not null");
            return this;
        }

        public Criteria andDUsuarioFecregistraEqualTo(Date value) {
            addCriterion("D_USUARIO_FECREGISTRA =", value, "dUsuarioFecregistra");
            return this;
        }

        public Criteria andDUsuarioFecregistraNotEqualTo(Date value) {
            addCriterion("D_USUARIO_FECREGISTRA <>", value, "dUsuarioFecregistra");
            return this;
        }

        public Criteria andDUsuarioFecregistraGreaterThan(Date value) {
            addCriterion("D_USUARIO_FECREGISTRA >", value, "dUsuarioFecregistra");
            return this;
        }

        public Criteria andDUsuarioFecregistraGreaterThanOrEqualTo(Date value) {
            addCriterion("D_USUARIO_FECREGISTRA >=", value, "dUsuarioFecregistra");
            return this;
        }

        public Criteria andDUsuarioFecregistraLessThan(Date value) {
            addCriterion("D_USUARIO_FECREGISTRA <", value, "dUsuarioFecregistra");
            return this;
        }

        public Criteria andDUsuarioFecregistraLessThanOrEqualTo(Date value) {
            addCriterion("D_USUARIO_FECREGISTRA <=", value, "dUsuarioFecregistra");
            return this;
        }

        public Criteria andDUsuarioFecregistraIn(List<Date> values) {
            addCriterion("D_USUARIO_FECREGISTRA in", values, "dUsuarioFecregistra");
            return this;
        }

        public Criteria andDUsuarioFecregistraNotIn(List<Date> values) {
            addCriterion("D_USUARIO_FECREGISTRA not in", values, "dUsuarioFecregistra");
            return this;
        }

        public Criteria andDUsuarioFecregistraBetween(Date value1, Date value2) {
            addCriterion("D_USUARIO_FECREGISTRA between", value1, value2, "dUsuarioFecregistra");
            return this;
        }

        public Criteria andDUsuarioFecregistraNotBetween(Date value1, Date value2) {
            addCriterion("D_USUARIO_FECREGISTRA not between", value1, value2, "dUsuarioFecregistra");
            return this;
        }

        public Criteria andDUsuarioFecmodificaIsNull() {
            addCriterion("D_USUARIO_FECMODIFICA is null");
            return this;
        }

        public Criteria andDUsuarioFecmodificaIsNotNull() {
            addCriterion("D_USUARIO_FECMODIFICA is not null");
            return this;
        }

        public Criteria andDUsuarioFecmodificaEqualTo(Date value) {
            addCriterion("D_USUARIO_FECMODIFICA =", value, "dUsuarioFecmodifica");
            return this;
        }

        public Criteria andDUsuarioFecmodificaNotEqualTo(Date value) {
            addCriterion("D_USUARIO_FECMODIFICA <>", value, "dUsuarioFecmodifica");
            return this;
        }

        public Criteria andDUsuarioFecmodificaGreaterThan(Date value) {
            addCriterion("D_USUARIO_FECMODIFICA >", value, "dUsuarioFecmodifica");
            return this;
        }

        public Criteria andDUsuarioFecmodificaGreaterThanOrEqualTo(Date value) {
            addCriterion("D_USUARIO_FECMODIFICA >=", value, "dUsuarioFecmodifica");
            return this;
        }

        public Criteria andDUsuarioFecmodificaLessThan(Date value) {
            addCriterion("D_USUARIO_FECMODIFICA <", value, "dUsuarioFecmodifica");
            return this;
        }

        public Criteria andDUsuarioFecmodificaLessThanOrEqualTo(Date value) {
            addCriterion("D_USUARIO_FECMODIFICA <=", value, "dUsuarioFecmodifica");
            return this;
        }

        public Criteria andDUsuarioFecmodificaIn(List<Date> values) {
            addCriterion("D_USUARIO_FECMODIFICA in", values, "dUsuarioFecmodifica");
            return this;
        }

        public Criteria andDUsuarioFecmodificaNotIn(List<Date> values) {
            addCriterion("D_USUARIO_FECMODIFICA not in", values, "dUsuarioFecmodifica");
            return this;
        }

        public Criteria andDUsuarioFecmodificaBetween(Date value1, Date value2) {
            addCriterion("D_USUARIO_FECMODIFICA between", value1, value2, "dUsuarioFecmodifica");
            return this;
        }

        public Criteria andDUsuarioFecmodificaNotBetween(Date value1, Date value2) {
            addCriterion("D_USUARIO_FECMODIFICA not between", value1, value2, "dUsuarioFecmodifica");
            return this;
        }

        public Criteria andVUsuarioDesusuregistraIsNull() {
            addCriterion("V_USUARIO_DESUSUREGISTRA is null");
            return this;
        }

        public Criteria andVUsuarioDesusuregistraIsNotNull() {
            addCriterion("V_USUARIO_DESUSUREGISTRA is not null");
            return this;
        }

        public Criteria andVUsuarioDesusuregistraEqualTo(String value) {
            addCriterion("V_USUARIO_DESUSUREGISTRA =", value, "vUsuarioDesusuregistra");
            return this;
        }

        public Criteria andVUsuarioDesusuregistraNotEqualTo(String value) {
            addCriterion("V_USUARIO_DESUSUREGISTRA <>", value, "vUsuarioDesusuregistra");
            return this;
        }

        public Criteria andVUsuarioDesusuregistraGreaterThan(String value) {
            addCriterion("V_USUARIO_DESUSUREGISTRA >", value, "vUsuarioDesusuregistra");
            return this;
        }

        public Criteria andVUsuarioDesusuregistraGreaterThanOrEqualTo(String value) {
            addCriterion("V_USUARIO_DESUSUREGISTRA >=", value, "vUsuarioDesusuregistra");
            return this;
        }

        public Criteria andVUsuarioDesusuregistraLessThan(String value) {
            addCriterion("V_USUARIO_DESUSUREGISTRA <", value, "vUsuarioDesusuregistra");
            return this;
        }

        public Criteria andVUsuarioDesusuregistraLessThanOrEqualTo(String value) {
            addCriterion("V_USUARIO_DESUSUREGISTRA <=", value, "vUsuarioDesusuregistra");
            return this;
        }

        public Criteria andVUsuarioDesusuregistraLike(String value) {
            addCriterion("V_USUARIO_DESUSUREGISTRA like", value, "vUsuarioDesusuregistra");
            return this;
        }

        public Criteria andVUsuarioDesusuregistraNotLike(String value) {
            addCriterion("V_USUARIO_DESUSUREGISTRA not like", value, "vUsuarioDesusuregistra");
            return this;
        }

        public Criteria andVUsuarioDesusuregistraIn(List<String> values) {
            addCriterion("V_USUARIO_DESUSUREGISTRA in", values, "vUsuarioDesusuregistra");
            return this;
        }

        public Criteria andVUsuarioDesusuregistraNotIn(List<String> values) {
            addCriterion("V_USUARIO_DESUSUREGISTRA not in", values, "vUsuarioDesusuregistra");
            return this;
        }

        public Criteria andVUsuarioDesusuregistraBetween(String value1, String value2) {
            addCriterion("V_USUARIO_DESUSUREGISTRA between", value1, value2, "vUsuarioDesusuregistra");
            return this;
        }

        public Criteria andVUsuarioDesusuregistraNotBetween(String value1, String value2) {
            addCriterion("V_USUARIO_DESUSUREGISTRA not between", value1, value2, "vUsuarioDesusuregistra");
            return this;
        }

        public Criteria andVUsuarioDesusumodificaIsNull() {
            addCriterion("V_USUARIO_DESUSUMODIFICA is null");
            return this;
        }

        public Criteria andVUsuarioDesusumodificaIsNotNull() {
            addCriterion("V_USUARIO_DESUSUMODIFICA is not null");
            return this;
        }

        public Criteria andVUsuarioDesusumodificaEqualTo(String value) {
            addCriterion("V_USUARIO_DESUSUMODIFICA =", value, "vUsuarioDesusumodifica");
            return this;
        }

        public Criteria andVUsuarioDesusumodificaNotEqualTo(String value) {
            addCriterion("V_USUARIO_DESUSUMODIFICA <>", value, "vUsuarioDesusumodifica");
            return this;
        }

        public Criteria andVUsuarioDesusumodificaGreaterThan(String value) {
            addCriterion("V_USUARIO_DESUSUMODIFICA >", value, "vUsuarioDesusumodifica");
            return this;
        }

        public Criteria andVUsuarioDesusumodificaGreaterThanOrEqualTo(String value) {
            addCriterion("V_USUARIO_DESUSUMODIFICA >=", value, "vUsuarioDesusumodifica");
            return this;
        }

        public Criteria andVUsuarioDesusumodificaLessThan(String value) {
            addCriterion("V_USUARIO_DESUSUMODIFICA <", value, "vUsuarioDesusumodifica");
            return this;
        }

        public Criteria andVUsuarioDesusumodificaLessThanOrEqualTo(String value) {
            addCriterion("V_USUARIO_DESUSUMODIFICA <=", value, "vUsuarioDesusumodifica");
            return this;
        }

        public Criteria andVUsuarioDesusumodificaLike(String value) {
            addCriterion("V_USUARIO_DESUSUMODIFICA like", value, "vUsuarioDesusumodifica");
            return this;
        }

        public Criteria andVUsuarioDesusumodificaNotLike(String value) {
            addCriterion("V_USUARIO_DESUSUMODIFICA not like", value, "vUsuarioDesusumodifica");
            return this;
        }

        public Criteria andVUsuarioDesusumodificaIn(List<String> values) {
            addCriterion("V_USUARIO_DESUSUMODIFICA in", values, "vUsuarioDesusumodifica");
            return this;
        }

        public Criteria andVUsuarioDesusumodificaNotIn(List<String> values) {
            addCriterion("V_USUARIO_DESUSUMODIFICA not in", values, "vUsuarioDesusumodifica");
            return this;
        }

        public Criteria andVUsuarioDesusumodificaBetween(String value1, String value2) {
            addCriterion("V_USUARIO_DESUSUMODIFICA between", value1, value2, "vUsuarioDesusumodifica");
            return this;
        }

        public Criteria andVUsuarioDesusumodificaNotBetween(String value1, String value2) {
            addCriterion("V_USUARIO_DESUSUMODIFICA not between", value1, value2, "vUsuarioDesusumodifica");
            return this;
        }

        public Criteria andVUsuarioDesipregistraIsNull() {
            addCriterion("V_USUARIO_DESIPREGISTRA is null");
            return this;
        }

        public Criteria andVUsuarioDesipregistraIsNotNull() {
            addCriterion("V_USUARIO_DESIPREGISTRA is not null");
            return this;
        }

        public Criteria andVUsuarioDesipregistraEqualTo(String value) {
            addCriterion("V_USUARIO_DESIPREGISTRA =", value, "vUsuarioDesipregistra");
            return this;
        }

        public Criteria andVUsuarioDesipregistraNotEqualTo(String value) {
            addCriterion("V_USUARIO_DESIPREGISTRA <>", value, "vUsuarioDesipregistra");
            return this;
        }

        public Criteria andVUsuarioDesipregistraGreaterThan(String value) {
            addCriterion("V_USUARIO_DESIPREGISTRA >", value, "vUsuarioDesipregistra");
            return this;
        }

        public Criteria andVUsuarioDesipregistraGreaterThanOrEqualTo(String value) {
            addCriterion("V_USUARIO_DESIPREGISTRA >=", value, "vUsuarioDesipregistra");
            return this;
        }

        public Criteria andVUsuarioDesipregistraLessThan(String value) {
            addCriterion("V_USUARIO_DESIPREGISTRA <", value, "vUsuarioDesipregistra");
            return this;
        }

        public Criteria andVUsuarioDesipregistraLessThanOrEqualTo(String value) {
            addCriterion("V_USUARIO_DESIPREGISTRA <=", value, "vUsuarioDesipregistra");
            return this;
        }

        public Criteria andVUsuarioDesipregistraLike(String value) {
            addCriterion("V_USUARIO_DESIPREGISTRA like", value, "vUsuarioDesipregistra");
            return this;
        }

        public Criteria andVUsuarioDesipregistraNotLike(String value) {
            addCriterion("V_USUARIO_DESIPREGISTRA not like", value, "vUsuarioDesipregistra");
            return this;
        }

        public Criteria andVUsuarioDesipregistraIn(List<String> values) {
            addCriterion("V_USUARIO_DESIPREGISTRA in", values, "vUsuarioDesipregistra");
            return this;
        }

        public Criteria andVUsuarioDesipregistraNotIn(List<String> values) {
            addCriterion("V_USUARIO_DESIPREGISTRA not in", values, "vUsuarioDesipregistra");
            return this;
        }

        public Criteria andVUsuarioDesipregistraBetween(String value1, String value2) {
            addCriterion("V_USUARIO_DESIPREGISTRA between", value1, value2, "vUsuarioDesipregistra");
            return this;
        }

        public Criteria andVUsuarioDesipregistraNotBetween(String value1, String value2) {
            addCriterion("V_USUARIO_DESIPREGISTRA not between", value1, value2, "vUsuarioDesipregistra");
            return this;
        }

        public Criteria andVUsuarioDesipmodificaIsNull() {
            addCriterion("V_USUARIO_DESIPMODIFICA is null");
            return this;
        }

        public Criteria andVUsuarioDesipmodificaIsNotNull() {
            addCriterion("V_USUARIO_DESIPMODIFICA is not null");
            return this;
        }

        public Criteria andVUsuarioDesipmodificaEqualTo(String value) {
            addCriterion("V_USUARIO_DESIPMODIFICA =", value, "vUsuarioDesipmodifica");
            return this;
        }

        public Criteria andVUsuarioDesipmodificaNotEqualTo(String value) {
            addCriterion("V_USUARIO_DESIPMODIFICA <>", value, "vUsuarioDesipmodifica");
            return this;
        }

        public Criteria andVUsuarioDesipmodificaGreaterThan(String value) {
            addCriterion("V_USUARIO_DESIPMODIFICA >", value, "vUsuarioDesipmodifica");
            return this;
        }

        public Criteria andVUsuarioDesipmodificaGreaterThanOrEqualTo(String value) {
            addCriterion("V_USUARIO_DESIPMODIFICA >=", value, "vUsuarioDesipmodifica");
            return this;
        }

        public Criteria andVUsuarioDesipmodificaLessThan(String value) {
            addCriterion("V_USUARIO_DESIPMODIFICA <", value, "vUsuarioDesipmodifica");
            return this;
        }

        public Criteria andVUsuarioDesipmodificaLessThanOrEqualTo(String value) {
            addCriterion("V_USUARIO_DESIPMODIFICA <=", value, "vUsuarioDesipmodifica");
            return this;
        }

        public Criteria andVUsuarioDesipmodificaLike(String value) {
            addCriterion("V_USUARIO_DESIPMODIFICA like", value, "vUsuarioDesipmodifica");
            return this;
        }

        public Criteria andVUsuarioDesipmodificaNotLike(String value) {
            addCriterion("V_USUARIO_DESIPMODIFICA not like", value, "vUsuarioDesipmodifica");
            return this;
        }

        public Criteria andVUsuarioDesipmodificaIn(List<String> values) {
            addCriterion("V_USUARIO_DESIPMODIFICA in", values, "vUsuarioDesipmodifica");
            return this;
        }

        public Criteria andVUsuarioDesipmodificaNotIn(List<String> values) {
            addCriterion("V_USUARIO_DESIPMODIFICA not in", values, "vUsuarioDesipmodifica");
            return this;
        }

        public Criteria andVUsuarioDesipmodificaBetween(String value1, String value2) {
            addCriterion("V_USUARIO_DESIPMODIFICA between", value1, value2, "vUsuarioDesipmodifica");
            return this;
        }

        public Criteria andVUsuarioDesipmodificaNotBetween(String value1, String value2) {
            addCriterion("V_USUARIO_DESIPMODIFICA not between", value1, value2, "vUsuarioDesipmodifica");
            return this;
        }

        public Criteria andIUsuarioEstadoIsNull() {
            addCriterion("I_USUARIO_ESTADO is null");
            return this;
        }

        public Criteria andIUsuarioEstadoIsNotNull() {
            addCriterion("I_USUARIO_ESTADO is not null");
            return this;
        }

        public Criteria andIUsuarioEstadoEqualTo(Integer value) {
            addCriterion("I_USUARIO_ESTADO =", value, "iUsuarioEstado");
            return this;
        }

        public Criteria andIUsuarioEstadoNotEqualTo(Integer value) {
            addCriterion("I_USUARIO_ESTADO <>", value, "iUsuarioEstado");
            return this;
        }

        public Criteria andIUsuarioEstadoGreaterThan(Integer value) {
            addCriterion("I_USUARIO_ESTADO >", value, "iUsuarioEstado");
            return this;
        }

        public Criteria andIUsuarioEstadoGreaterThanOrEqualTo(Integer value) {
            addCriterion("I_USUARIO_ESTADO >=", value, "iUsuarioEstado");
            return this;
        }

        public Criteria andIUsuarioEstadoLessThan(Integer value) {
            addCriterion("I_USUARIO_ESTADO <", value, "iUsuarioEstado");
            return this;
        }

        public Criteria andIUsuarioEstadoLessThanOrEqualTo(Integer value) {
            addCriterion("I_USUARIO_ESTADO <=", value, "iUsuarioEstado");
            return this;
        }

        public Criteria andIUsuarioEstadoIn(List<Integer> values) {
            addCriterion("I_USUARIO_ESTADO in", values, "iUsuarioEstado");
            return this;
        }

        public Criteria andIUsuarioEstadoNotIn(List<Integer> values) {
            addCriterion("I_USUARIO_ESTADO not in", values, "iUsuarioEstado");
            return this;
        }

        public Criteria andIUsuarioEstadoBetween(Integer value1, Integer value2) {
            addCriterion("I_USUARIO_ESTADO between", value1, value2, "iUsuarioEstado");
            return this;
        }

        public Criteria andIUsuarioEstadoNotBetween(Integer value1, Integer value2) {
            addCriterion("I_USUARIO_ESTADO not between", value1, value2, "iUsuarioEstado");
            return this;
        }

        public Criteria andIUsuarioSexoIsNull() {
            addCriterion("I_USUARIO_SEXO is null");
            return this;
        }

        public Criteria andIUsuarioSexoIsNotNull() {
            addCriterion("I_USUARIO_SEXO is not null");
            return this;
        }

        public Criteria andIUsuarioSexoEqualTo(Integer value) {
            addCriterion("I_USUARIO_SEXO =", value, "iUsuarioSexo");
            return this;
        }

        public Criteria andIUsuarioSexoNotEqualTo(Integer value) {
            addCriterion("I_USUARIO_SEXO <>", value, "iUsuarioSexo");
            return this;
        }

        public Criteria andIUsuarioSexoGreaterThan(Integer value) {
            addCriterion("I_USUARIO_SEXO >", value, "iUsuarioSexo");
            return this;
        }

        public Criteria andIUsuarioSexoGreaterThanOrEqualTo(Integer value) {
            addCriterion("I_USUARIO_SEXO >=", value, "iUsuarioSexo");
            return this;
        }

        public Criteria andIUsuarioSexoLessThan(Integer value) {
            addCriterion("I_USUARIO_SEXO <", value, "iUsuarioSexo");
            return this;
        }

        public Criteria andIUsuarioSexoLessThanOrEqualTo(Integer value) {
            addCriterion("I_USUARIO_SEXO <=", value, "iUsuarioSexo");
            return this;
        }

        public Criteria andIUsuarioSexoIn(List<Integer> values) {
            addCriterion("I_USUARIO_SEXO in", values, "iUsuarioSexo");
            return this;
        }

        public Criteria andIUsuarioSexoNotIn(List<Integer> values) {
            addCriterion("I_USUARIO_SEXO not in", values, "iUsuarioSexo");
            return this;
        }

        public Criteria andIUsuarioSexoBetween(Integer value1, Integer value2) {
            addCriterion("I_USUARIO_SEXO between", value1, value2, "iUsuarioSexo");
            return this;
        }

        public Criteria andIUsuarioSexoNotBetween(Integer value1, Integer value2) {
            addCriterion("I_USUARIO_SEXO not between", value1, value2, "iUsuarioSexo");
            return this;
        }

        public Criteria andDUsuarioFecnacimientoIsNull() {
            addCriterion("D_USUARIO_FECNACIMIENTO is null");
            return this;
        }

        public Criteria andDUsuarioFecnacimientoIsNotNull() {
            addCriterion("D_USUARIO_FECNACIMIENTO is not null");
            return this;
        }

        public Criteria andDUsuarioFecnacimientoEqualTo(Date value) {
            addCriterion("D_USUARIO_FECNACIMIENTO =", value, "dUsuarioFecnacimiento");
            return this;
        }

        public Criteria andDUsuarioFecnacimientoNotEqualTo(Date value) {
            addCriterion("D_USUARIO_FECNACIMIENTO <>", value, "dUsuarioFecnacimiento");
            return this;
        }

        public Criteria andDUsuarioFecnacimientoGreaterThan(Date value) {
            addCriterion("D_USUARIO_FECNACIMIENTO >", value, "dUsuarioFecnacimiento");
            return this;
        }

        public Criteria andDUsuarioFecnacimientoGreaterThanOrEqualTo(Date value) {
            addCriterion("D_USUARIO_FECNACIMIENTO >=", value, "dUsuarioFecnacimiento");
            return this;
        }

        public Criteria andDUsuarioFecnacimientoLessThan(Date value) {
            addCriterion("D_USUARIO_FECNACIMIENTO <", value, "dUsuarioFecnacimiento");
            return this;
        }

        public Criteria andDUsuarioFecnacimientoLessThanOrEqualTo(Date value) {
            addCriterion("D_USUARIO_FECNACIMIENTO <=", value, "dUsuarioFecnacimiento");
            return this;
        }

        public Criteria andDUsuarioFecnacimientoIn(List<Date> values) {
            addCriterion("D_USUARIO_FECNACIMIENTO in", values, "dUsuarioFecnacimiento");
            return this;
        }

        public Criteria andDUsuarioFecnacimientoNotIn(List<Date> values) {
            addCriterion("D_USUARIO_FECNACIMIENTO not in", values, "dUsuarioFecnacimiento");
            return this;
        }

        public Criteria andDUsuarioFecnacimientoBetween(Date value1, Date value2) {
            addCriterion("D_USUARIO_FECNACIMIENTO between", value1, value2, "dUsuarioFecnacimiento");
            return this;
        }

        public Criteria andDUsuarioFecnacimientoNotBetween(Date value1, Date value2) {
            addCriterion("D_USUARIO_FECNACIMIENTO not between", value1, value2, "dUsuarioFecnacimiento");
            return this;
        }

        public Criteria andVUsuarioEmailIsNull() {
            addCriterion("V_USUARIO_EMAIL is null");
            return this;
        }

        public Criteria andVUsuarioEmailIsNotNull() {
            addCriterion("V_USUARIO_EMAIL is not null");
            return this;
        }

        public Criteria andVUsuarioEmailEqualTo(String value) {
            addCriterion("V_USUARIO_EMAIL =", value, "vUsuarioEmail");
            return this;
        }

        public Criteria andVUsuarioEmailNotEqualTo(String value) {
            addCriterion("V_USUARIO_EMAIL <>", value, "vUsuarioEmail");
            return this;
        }

        public Criteria andVUsuarioEmailGreaterThan(String value) {
            addCriterion("V_USUARIO_EMAIL >", value, "vUsuarioEmail");
            return this;
        }

        public Criteria andVUsuarioEmailGreaterThanOrEqualTo(String value) {
            addCriterion("V_USUARIO_EMAIL >=", value, "vUsuarioEmail");
            return this;
        }

        public Criteria andVUsuarioEmailLessThan(String value) {
            addCriterion("V_USUARIO_EMAIL <", value, "vUsuarioEmail");
            return this;
        }

        public Criteria andVUsuarioEmailLessThanOrEqualTo(String value) {
            addCriterion("V_USUARIO_EMAIL <=", value, "vUsuarioEmail");
            return this;
        }

        public Criteria andVUsuarioEmailLike(String value) {
            addCriterion("V_USUARIO_EMAIL like", value, "vUsuarioEmail");
            return this;
        }

        public Criteria andVUsuarioEmailNotLike(String value) {
            addCriterion("V_USUARIO_EMAIL not like", value, "vUsuarioEmail");
            return this;
        }

        public Criteria andVUsuarioEmailIn(List<String> values) {
            addCriterion("V_USUARIO_EMAIL in", values, "vUsuarioEmail");
            return this;
        }

        public Criteria andVUsuarioEmailNotIn(List<String> values) {
            addCriterion("V_USUARIO_EMAIL not in", values, "vUsuarioEmail");
            return this;
        }

        public Criteria andVUsuarioEmailBetween(String value1, String value2) {
            addCriterion("V_USUARIO_EMAIL between", value1, value2, "vUsuarioEmail");
            return this;
        }

        public Criteria andVUsuarioEmailNotBetween(String value1, String value2) {
            addCriterion("V_USUARIO_EMAIL not between", value1, value2, "vUsuarioEmail");
            return this;
        }

        public Criteria andIUsuarioIndhabilitadoIsNull() {
            addCriterion("I_USUARIO_INDHABILITADO is null");
            return this;
        }

        public Criteria andIUsuarioIndhabilitadoIsNotNull() {
            addCriterion("I_USUARIO_INDHABILITADO is not null");
            return this;
        }

        public Criteria andIUsuarioIndhabilitadoEqualTo(Integer value) {
            addCriterion("I_USUARIO_INDHABILITADO =", value, "iUsuarioIndhabilitado");
            return this;
        }

        public Criteria andIUsuarioIndhabilitadoNotEqualTo(Integer value) {
            addCriterion("I_USUARIO_INDHABILITADO <>", value, "iUsuarioIndhabilitado");
            return this;
        }

        public Criteria andIUsuarioIndhabilitadoGreaterThan(Integer value) {
            addCriterion("I_USUARIO_INDHABILITADO >", value, "iUsuarioIndhabilitado");
            return this;
        }

        public Criteria andIUsuarioIndhabilitadoGreaterThanOrEqualTo(Integer value) {
            addCriterion("I_USUARIO_INDHABILITADO >=", value, "iUsuarioIndhabilitado");
            return this;
        }

        public Criteria andIUsuarioIndhabilitadoLessThan(Integer value) {
            addCriterion("I_USUARIO_INDHABILITADO <", value, "iUsuarioIndhabilitado");
            return this;
        }

        public Criteria andIUsuarioIndhabilitadoLessThanOrEqualTo(Integer value) {
            addCriterion("I_USUARIO_INDHABILITADO <=", value, "iUsuarioIndhabilitado");
            return this;
        }

        public Criteria andIUsuarioIndhabilitadoIn(List<Integer> values) {
            addCriterion("I_USUARIO_INDHABILITADO in", values, "iUsuarioIndhabilitado");
            return this;
        }

        public Criteria andIUsuarioIndhabilitadoNotIn(List<Integer> values) {
            addCriterion("I_USUARIO_INDHABILITADO not in", values, "iUsuarioIndhabilitado");
            return this;
        }

        public Criteria andIUsuarioIndhabilitadoBetween(Integer value1, Integer value2) {
            addCriterion("I_USUARIO_INDHABILITADO between", value1, value2, "iUsuarioIndhabilitado");
            return this;
        }

        public Criteria andIUsuarioIndhabilitadoNotBetween(Integer value1, Integer value2) {
            addCriterion("I_USUARIO_INDHABILITADO not between", value1, value2, "iUsuarioIndhabilitado");
            return this;
        }

        public Criteria andVUsuarioBgApplicationIsNull() {
            addCriterion("V_USUARIO_BG_APPLICATION is null");
            return this;
        }

        public Criteria andVUsuarioBgApplicationIsNotNull() {
            addCriterion("V_USUARIO_BG_APPLICATION is not null");
            return this;
        }

        public Criteria andVUsuarioBgApplicationEqualTo(String value) {
            addCriterion("V_USUARIO_BG_APPLICATION =", value, "vUsuarioBgApplication");
            return this;
        }

        public Criteria andVUsuarioBgApplicationNotEqualTo(String value) {
            addCriterion("V_USUARIO_BG_APPLICATION <>", value, "vUsuarioBgApplication");
            return this;
        }

        public Criteria andVUsuarioBgApplicationGreaterThan(String value) {
            addCriterion("V_USUARIO_BG_APPLICATION >", value, "vUsuarioBgApplication");
            return this;
        }

        public Criteria andVUsuarioBgApplicationGreaterThanOrEqualTo(String value) {
            addCriterion("V_USUARIO_BG_APPLICATION >=", value, "vUsuarioBgApplication");
            return this;
        }

        public Criteria andVUsuarioBgApplicationLessThan(String value) {
            addCriterion("V_USUARIO_BG_APPLICATION <", value, "vUsuarioBgApplication");
            return this;
        }

        public Criteria andVUsuarioBgApplicationLessThanOrEqualTo(String value) {
            addCriterion("V_USUARIO_BG_APPLICATION <=", value, "vUsuarioBgApplication");
            return this;
        }

        public Criteria andVUsuarioBgApplicationLike(String value) {
            addCriterion("V_USUARIO_BG_APPLICATION like", value, "vUsuarioBgApplication");
            return this;
        }

        public Criteria andVUsuarioBgApplicationNotLike(String value) {
            addCriterion("V_USUARIO_BG_APPLICATION not like", value, "vUsuarioBgApplication");
            return this;
        }

        public Criteria andVUsuarioBgApplicationIn(List<String> values) {
            addCriterion("V_USUARIO_BG_APPLICATION in", values, "vUsuarioBgApplication");
            return this;
        }

        public Criteria andVUsuarioBgApplicationNotIn(List<String> values) {
            addCriterion("V_USUARIO_BG_APPLICATION not in", values, "vUsuarioBgApplication");
            return this;
        }

        public Criteria andVUsuarioBgApplicationBetween(String value1, String value2) {
            addCriterion("V_USUARIO_BG_APPLICATION between", value1, value2, "vUsuarioBgApplication");
            return this;
        }

        public Criteria andVUsuarioBgApplicationNotBetween(String value1, String value2) {
            addCriterion("V_USUARIO_BG_APPLICATION not between", value1, value2, "vUsuarioBgApplication");
            return this;
        }
    }
}