package pe.gob.ep.ginnet.catalogo.dao.ibatis;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.ginnet.catalogo.bean.ElementoCatalogo;
import pe.gob.ep.ginnet.catalogo.bean.ElementoCatalogoCriteria;
import pe.gob.ep.ginnet.catalogo.dao.ElementoCatalogoDAO;

public class ElementoCatalogoDAOImpl extends SqlMapClientDaoSupport implements ElementoCatalogoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WILLIAN.CTRL_CONF_CATALOGO
     *
     * @ibatorgenerated
     */
    public ElementoCatalogoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WILLIAN.CTRL_CONF_CATALOGO
     *
     * @ibatorgenerated
     */
    public int countByExample(ElementoCatalogoCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("WILLIAN_CTRL_CONF_CATALOGO.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WILLIAN.CTRL_CONF_CATALOGO
     *
     * @ibatorgenerated
     */
    public int deleteByExample(ElementoCatalogoCriteria example) {
        int rows = getSqlMapClientTemplate().delete("WILLIAN_CTRL_CONF_CATALOGO.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WILLIAN.CTRL_CONF_CATALOGO
     *
     * @ibatorgenerated
     */
    public void insert(ElementoCatalogo record) {
        getSqlMapClientTemplate().insert("WILLIAN_CTRL_CONF_CATALOGO.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WILLIAN.CTRL_CONF_CATALOGO
     *
     * @ibatorgenerated
     */
    public void insertSelective(ElementoCatalogo record) {
        getSqlMapClientTemplate().insert("WILLIAN_CTRL_CONF_CATALOGO.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WILLIAN.CTRL_CONF_CATALOGO
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<ElementoCatalogo> selectByExample(ElementoCatalogoCriteria example) {
    	System.out.println("dentro de dao...");
        List<ElementoCatalogo> list = getSqlMapClientTemplate().queryForList("WILLIAN_CTRL_CONF_CATALOGO.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WILLIAN.CTRL_CONF_CATALOGO
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(ElementoCatalogo record, ElementoCatalogoCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("WILLIAN_CTRL_CONF_CATALOGO.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WILLIAN.CTRL_CONF_CATALOGO
     *
     * @ibatorgenerated
     */
    public int updateByExample(ElementoCatalogo record, ElementoCatalogoCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("WILLIAN_CTRL_CONF_CATALOGO.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table WILLIAN.CTRL_CONF_CATALOGO
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends ElementoCatalogoCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, ElementoCatalogoCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}