package pe.gob.ep.ginnet.catalogo.dao;

import java.util.List;

import pe.gob.ep.ginnet.catalogo.bean.ElementoCatalogo;
import pe.gob.ep.ginnet.catalogo.bean.ElementoCatalogoCriteria;

public interface ElementoCatalogoDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WILLIAN.CTRL_CONF_CATALOGO
     *
     * @ibatorgenerated
     */
    int countByExample(ElementoCatalogoCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WILLIAN.CTRL_CONF_CATALOGO
     *
     * @ibatorgenerated
     */
    int deleteByExample(ElementoCatalogoCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WILLIAN.CTRL_CONF_CATALOGO
     *
     * @ibatorgenerated
     */
    void insert(ElementoCatalogo record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WILLIAN.CTRL_CONF_CATALOGO
     *
     * @ibatorgenerated
     */
    void insertSelective(ElementoCatalogo record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WILLIAN.CTRL_CONF_CATALOGO
     *
     * @ibatorgenerated
     */
    List<ElementoCatalogo> selectByExample(ElementoCatalogoCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WILLIAN.CTRL_CONF_CATALOGO
     *
     * @ibatorgenerated
     */
    int updateByExampleSelective(ElementoCatalogo record, ElementoCatalogoCriteria example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WILLIAN.CTRL_CONF_CATALOGO
     *
     * @ibatorgenerated
     */
    int updateByExample(ElementoCatalogo record, ElementoCatalogoCriteria example);
}