package pe.gob.ep.ginnet.radamanthys.bean;

public class Docente {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_docente.id_docente
     *
     * @ibatorgenerated
     */
    private Integer idDocente;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_docente.nombre
     *
     * @ibatorgenerated
     */
    private String nombre;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_docente.apaterno
     *
     * @ibatorgenerated
     */
    private String apaterno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_docente.amaterno
     *
     * @ibatorgenerated
     */
    private String amaterno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_docente.dni
     *
     * @ibatorgenerated
     */
    private String dni;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_docente.email
     *
     * @ibatorgenerated
     */
    private String email;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_docente.id_docente
     *
     * @return the value of tbl_docente.id_docente
     *
     * @ibatorgenerated
     */
    
    private String nombreCompleto;    
    
    public String getNombreCompleto() {
		return nombreCompleto;
	}

	public void setNombreCompleto(String nombreCompleto) {
		this.nombreCompleto = nombreCompleto;
	}

	public Integer getIdDocente() {
        return idDocente;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_docente.id_docente
     *
     * @param idDocente the value for tbl_docente.id_docente
     *
     * @ibatorgenerated
     */
    public void setIdDocente(Integer idDocente) {
        this.idDocente = idDocente;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_docente.nombre
     *
     * @return the value of tbl_docente.nombre
     *
     * @ibatorgenerated
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_docente.nombre
     *
     * @param nombre the value for tbl_docente.nombre
     *
     * @ibatorgenerated
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_docente.apaterno
     *
     * @return the value of tbl_docente.apaterno
     *
     * @ibatorgenerated
     */
    public String getApaterno() {
        return apaterno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_docente.apaterno
     *
     * @param apaterno the value for tbl_docente.apaterno
     *
     * @ibatorgenerated
     */
    public void setApaterno(String apaterno) {
        this.apaterno = apaterno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_docente.amaterno
     *
     * @return the value of tbl_docente.amaterno
     *
     * @ibatorgenerated
     */
    public String getAmaterno() {
        return amaterno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_docente.amaterno
     *
     * @param amaterno the value for tbl_docente.amaterno
     *
     * @ibatorgenerated
     */
    public void setAmaterno(String amaterno) {
        this.amaterno = amaterno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_docente.dni
     *
     * @return the value of tbl_docente.dni
     *
     * @ibatorgenerated
     */
    public String getDni() {
        return dni;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_docente.dni
     *
     * @param dni the value for tbl_docente.dni
     *
     * @ibatorgenerated
     */
    public void setDni(String dni) {
        this.dni = dni;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_docente.email
     *
     * @return the value of tbl_docente.email
     *
     * @ibatorgenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_docente.email
     *
     * @param email the value for tbl_docente.email
     *
     * @ibatorgenerated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_docente
     *
     * @ibatorgenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof Docente)) {
            return false;
        }
        Docente other = (Docente) that;
        return this.getIdDocente() == null ? other == null : this.getIdDocente().equals(other.getIdDocente())
            && this.getNombre() == null ? other == null : this.getNombre().equals(other.getNombre())
            && this.getApaterno() == null ? other == null : this.getApaterno().equals(other.getApaterno())
            && this.getAmaterno() == null ? other == null : this.getAmaterno().equals(other.getAmaterno())
            && this.getDni() == null ? other == null : this.getDni().equals(other.getDni())
            && this.getEmail() == null ? other == null : this.getEmail().equals(other.getEmail());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_docente
     *
     * @ibatorgenerated
     */
    @Override
    public int hashCode() {
        int hash = 23;
        if (getIdDocente() != null) {
            hash *= getIdDocente().hashCode();
        }
        if (getNombre() != null) {
            hash *= getNombre().hashCode();
        }
        if (getApaterno() != null) {
            hash *= getApaterno().hashCode();
        }
        if (getAmaterno() != null) {
            hash *= getAmaterno().hashCode();
        }
        if (getDni() != null) {
            hash *= getDni().hashCode();
        }
        if (getEmail() != null) {
            hash *= getEmail().hashCode();
        }
        return hash;
    }
}