package pe.gob.ep.ginnet.radamanthys.bean;

import java.util.List;

public class Examen {
    
    private Integer id;    
    private String descripcion;
    private Integer idCurso;
    private Integer idSistema;
    private Integer idEstado;
    private List<Alternativa> alternativa;

    public Integer getId() {
        return id;
    }

    
	public List<Alternativa> getAlternativa() {
		return alternativa;
	}


	public void setAlternativa(List<Alternativa> alternativa) {
		this.alternativa = alternativa;
	}


	/**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_examen.id
     *
     * @param id the value for tbl_examen.id
     *
     * @ibatorgenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_examen.descripcion
     *
     * @return the value of tbl_examen.descripcion
     *
     * @ibatorgenerated
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_examen.descripcion
     *
     * @param descripcion the value for tbl_examen.descripcion
     *
     * @ibatorgenerated
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_examen.id_curso
     *
     * @return the value of tbl_examen.id_curso
     *
     * @ibatorgenerated
     */
    public Integer getIdCurso() {
        return idCurso;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_examen.id_curso
     *
     * @param idCurso the value for tbl_examen.id_curso
     *
     * @ibatorgenerated
     */
    public void setIdCurso(Integer idCurso) {
        this.idCurso = idCurso;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_examen.id_sistema
     *
     * @return the value of tbl_examen.id_sistema
     *
     * @ibatorgenerated
     */
    public Integer getIdSistema() {
        return idSistema;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_examen.id_sistema
     *
     * @param idSistema the value for tbl_examen.id_sistema
     *
     * @ibatorgenerated
     */
    public void setIdSistema(Integer idSistema) {
        this.idSistema = idSistema;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_examen.id_estado
     *
     * @return the value of tbl_examen.id_estado
     *
     * @ibatorgenerated
     */
    public Integer getIdEstado() {
        return idEstado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_examen.id_estado
     *
     * @param idEstado the value for tbl_examen.id_estado
     *
     * @ibatorgenerated
     */
    public void setIdEstado(Integer idEstado) {
        this.idEstado = idEstado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_examen
     *
     * @ibatorgenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof Examen)) {
            return false;
        }
        Examen other = (Examen) that;
        return this.getId() == null ? other == null : this.getId().equals(other.getId())
            && this.getDescripcion() == null ? other == null : this.getDescripcion().equals(other.getDescripcion())
            && this.getIdCurso() == null ? other == null : this.getIdCurso().equals(other.getIdCurso())
            && this.getIdSistema() == null ? other == null : this.getIdSistema().equals(other.getIdSistema())
            && this.getIdEstado() == null ? other == null : this.getIdEstado().equals(other.getIdEstado());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_examen
     *
     * @ibatorgenerated
     */
    @Override
    public int hashCode() {
        int hash = 23;
        if (getId() != null) {
            hash *= getId().hashCode();
        }
        if (getDescripcion() != null) {
            hash *= getDescripcion().hashCode();
        }
        if (getIdCurso() != null) {
            hash *= getIdCurso().hashCode();
        }
        if (getIdSistema() != null) {
            hash *= getIdSistema().hashCode();
        }
        if (getIdEstado() != null) {
            hash *= getIdEstado().hashCode();
        }
        return hash;
    }
}