package pe.gob.ep.ginnet.radamanthys.bean;

public class Persona {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_persona.codigo
     *
     * @ibatorgenerated
     */
    private Integer codigo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_persona.nombres
     *
     * @ibatorgenerated
     */
    private String nombres;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_persona.apaterno
     *
     * @ibatorgenerated
     */
    private String apaterno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_persona.amaterno
     *
     * @ibatorgenerated
     */
    private String amaterno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_persona.tipo
     *
     * @ibatorgenerated
     */
    private Integer tipo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_persona.correo
     *
     * @ibatorgenerated
     */
    private String correo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_persona.login
     *
     * @ibatorgenerated
     */
    private String login;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_persona.clave
     *
     * @ibatorgenerated
     */
    private String clave;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_persona.codigo
     *
     * @return the value of tbl_persona.codigo
     *
     * @ibatorgenerated
     */
    public Integer getCodigo() {
        return codigo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_persona.codigo
     *
     * @param codigo the value for tbl_persona.codigo
     *
     * @ibatorgenerated
     */
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_persona.nombres
     *
     * @return the value of tbl_persona.nombres
     *
     * @ibatorgenerated
     */
    public String getNombres() {
        return nombres;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_persona.nombres
     *
     * @param nombres the value for tbl_persona.nombres
     *
     * @ibatorgenerated
     */
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_persona.apaterno
     *
     * @return the value of tbl_persona.apaterno
     *
     * @ibatorgenerated
     */
    public String getApaterno() {
        return apaterno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_persona.apaterno
     *
     * @param apaterno the value for tbl_persona.apaterno
     *
     * @ibatorgenerated
     */
    public void setApaterno(String apaterno) {
        this.apaterno = apaterno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_persona.amaterno
     *
     * @return the value of tbl_persona.amaterno
     *
     * @ibatorgenerated
     */
    public String getAmaterno() {
        return amaterno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_persona.amaterno
     *
     * @param amaterno the value for tbl_persona.amaterno
     *
     * @ibatorgenerated
     */
    public void setAmaterno(String amaterno) {
        this.amaterno = amaterno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_persona.tipo
     *
     * @return the value of tbl_persona.tipo
     *
     * @ibatorgenerated
     */
    public Integer getTipo() {
        return tipo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_persona.tipo
     *
     * @param tipo the value for tbl_persona.tipo
     *
     * @ibatorgenerated
     */
    public void setTipo(Integer tipo) {
        this.tipo = tipo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_persona.correo
     *
     * @return the value of tbl_persona.correo
     *
     * @ibatorgenerated
     */
    public String getCorreo() {
        return correo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_persona.correo
     *
     * @param correo the value for tbl_persona.correo
     *
     * @ibatorgenerated
     */
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_persona.login
     *
     * @return the value of tbl_persona.login
     *
     * @ibatorgenerated
     */
    public String getLogin() {
        return login;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_persona.login
     *
     * @param login the value for tbl_persona.login
     *
     * @ibatorgenerated
     */
    public void setLogin(String login) {
        this.login = login;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_persona.clave
     *
     * @return the value of tbl_persona.clave
     *
     * @ibatorgenerated
     */
    public String getClave() {
        return clave;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_persona.clave
     *
     * @param clave the value for tbl_persona.clave
     *
     * @ibatorgenerated
     */
    public void setClave(String clave) {
        this.clave = clave;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_persona
     *
     * @ibatorgenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof Persona)) {
            return false;
        }
        Persona other = (Persona) that;
        return this.getCodigo() == null ? other == null : this.getCodigo().equals(other.getCodigo())
            && this.getNombres() == null ? other == null : this.getNombres().equals(other.getNombres())
            && this.getApaterno() == null ? other == null : this.getApaterno().equals(other.getApaterno())
            && this.getAmaterno() == null ? other == null : this.getAmaterno().equals(other.getAmaterno())
            && this.getTipo() == null ? other == null : this.getTipo().equals(other.getTipo())
            && this.getCorreo() == null ? other == null : this.getCorreo().equals(other.getCorreo())
            && this.getLogin() == null ? other == null : this.getLogin().equals(other.getLogin())
            && this.getClave() == null ? other == null : this.getClave().equals(other.getClave());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_persona
     *
     * @ibatorgenerated
     */
    @Override
    public int hashCode() {
        int hash = 23;
        if (getCodigo() != null) {
            hash *= getCodigo().hashCode();
        }
        if (getNombres() != null) {
            hash *= getNombres().hashCode();
        }
        if (getApaterno() != null) {
            hash *= getApaterno().hashCode();
        }
        if (getAmaterno() != null) {
            hash *= getAmaterno().hashCode();
        }
        if (getTipo() != null) {
            hash *= getTipo().hashCode();
        }
        if (getCorreo() != null) {
            hash *= getCorreo().hashCode();
        }
        if (getLogin() != null) {
            hash *= getLogin().hashCode();
        }
        if (getClave() != null) {
            hash *= getClave().hashCode();
        }
        return hash;
    }
}