package pe.gob.ep.ginnet.radamanthys.bean;

public class ProfesorCurso {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_profesor_curso.id
     *
     * @ibatorgenerated
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_profesor_curso.id_profesor
     *
     * @ibatorgenerated
     */
    private Integer idProfesor;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_profesor_curso.id_curso
     *
     * @ibatorgenerated
     */
    private Integer idCurso;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_profesor_curso.id
     *
     * @return the value of tbl_profesor_curso.id
     *
     * @ibatorgenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_profesor_curso.id
     *
     * @param id the value for tbl_profesor_curso.id
     *
     * @ibatorgenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_profesor_curso.id_profesor
     *
     * @return the value of tbl_profesor_curso.id_profesor
     *
     * @ibatorgenerated
     */
    public Integer getIdProfesor() {
        return idProfesor;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_profesor_curso.id_profesor
     *
     * @param idProfesor the value for tbl_profesor_curso.id_profesor
     *
     * @ibatorgenerated
     */
    public void setIdProfesor(Integer idProfesor) {
        this.idProfesor = idProfesor;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_profesor_curso.id_curso
     *
     * @return the value of tbl_profesor_curso.id_curso
     *
     * @ibatorgenerated
     */
    public Integer getIdCurso() {
        return idCurso;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_profesor_curso.id_curso
     *
     * @param idCurso the value for tbl_profesor_curso.id_curso
     *
     * @ibatorgenerated
     */
    public void setIdCurso(Integer idCurso) {
        this.idCurso = idCurso;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_profesor_curso
     *
     * @ibatorgenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof ProfesorCurso)) {
            return false;
        }
        ProfesorCurso other = (ProfesorCurso) that;
        return this.getId() == null ? other == null : this.getId().equals(other.getId())
            && this.getIdProfesor() == null ? other == null : this.getIdProfesor().equals(other.getIdProfesor())
            && this.getIdCurso() == null ? other == null : this.getIdCurso().equals(other.getIdCurso());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_profesor_curso
     *
     * @ibatorgenerated
     */
    @Override
    public int hashCode() {
        int hash = 23;
        if (getId() != null) {
            hash *= getId().hashCode();
        }
        if (getIdProfesor() != null) {
            hash *= getIdProfesor().hashCode();
        }
        if (getIdCurso() != null) {
            hash *= getIdCurso().hashCode();
        }
        return hash;
    }
}