package pe.gob.ep.ginnet.radamanthys.bean;

public class Resultado {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_resultado.id
     *
     * @ibatorgenerated
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_resultado.id_alumno
     *
     * @ibatorgenerated
     */
    private Integer idAlumno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_resultado.id_curso
     *
     * @ibatorgenerated
     */
    private Integer idCurso;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_resultado.nota
     *
     * @ibatorgenerated
     */
    private Integer nota;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_resultado.num_preg_correctas
     *
     * @ibatorgenerated
     */
    private Integer numPregCorrectas;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_resultado.num_preg_incorrectas
     *
     * @ibatorgenerated
     */
    private Integer numPregIncorrectas;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_resultado.condicion
     *
     * @ibatorgenerated
     */
    private String condicion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_resultado.ruta_archivo
     *
     * @ibatorgenerated
     */
    private String rutaArchivo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_resultado.estado
     *
     * @ibatorgenerated
     */
    private Integer estado;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_resultado.id
     *
     * @return the value of tbl_resultado.id
     *
     * @ibatorgenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_resultado.id
     *
     * @param id the value for tbl_resultado.id
     *
     * @ibatorgenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_resultado.id_alumno
     *
     * @return the value of tbl_resultado.id_alumno
     *
     * @ibatorgenerated
     */
    public Integer getIdAlumno() {
        return idAlumno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_resultado.id_alumno
     *
     * @param idAlumno the value for tbl_resultado.id_alumno
     *
     * @ibatorgenerated
     */
    public void setIdAlumno(Integer idAlumno) {
        this.idAlumno = idAlumno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_resultado.id_curso
     *
     * @return the value of tbl_resultado.id_curso
     *
     * @ibatorgenerated
     */
    public Integer getIdCurso() {
        return idCurso;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_resultado.id_curso
     *
     * @param idCurso the value for tbl_resultado.id_curso
     *
     * @ibatorgenerated
     */
    public void setIdCurso(Integer idCurso) {
        this.idCurso = idCurso;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_resultado.nota
     *
     * @return the value of tbl_resultado.nota
     *
     * @ibatorgenerated
     */
    public Integer getNota() {
        return nota;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_resultado.nota
     *
     * @param nota the value for tbl_resultado.nota
     *
     * @ibatorgenerated
     */
    public void setNota(Integer nota) {
        this.nota = nota;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_resultado.num_preg_correctas
     *
     * @return the value of tbl_resultado.num_preg_correctas
     *
     * @ibatorgenerated
     */
    public Integer getNumPregCorrectas() {
        return numPregCorrectas;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_resultado.num_preg_correctas
     *
     * @param numPregCorrectas the value for tbl_resultado.num_preg_correctas
     *
     * @ibatorgenerated
     */
    public void setNumPregCorrectas(Integer numPregCorrectas) {
        this.numPregCorrectas = numPregCorrectas;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_resultado.num_preg_incorrectas
     *
     * @return the value of tbl_resultado.num_preg_incorrectas
     *
     * @ibatorgenerated
     */
    public Integer getNumPregIncorrectas() {
        return numPregIncorrectas;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_resultado.num_preg_incorrectas
     *
     * @param numPregIncorrectas the value for tbl_resultado.num_preg_incorrectas
     *
     * @ibatorgenerated
     */
    public void setNumPregIncorrectas(Integer numPregIncorrectas) {
        this.numPregIncorrectas = numPregIncorrectas;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_resultado.condicion
     *
     * @return the value of tbl_resultado.condicion
     *
     * @ibatorgenerated
     */
    public String getCondicion() {
        return condicion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_resultado.condicion
     *
     * @param condicion the value for tbl_resultado.condicion
     *
     * @ibatorgenerated
     */
    public void setCondicion(String condicion) {
        this.condicion = condicion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_resultado.ruta_archivo
     *
     * @return the value of tbl_resultado.ruta_archivo
     *
     * @ibatorgenerated
     */
    public String getRutaArchivo() {
        return rutaArchivo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_resultado.ruta_archivo
     *
     * @param rutaArchivo the value for tbl_resultado.ruta_archivo
     *
     * @ibatorgenerated
     */
    public void setRutaArchivo(String rutaArchivo) {
        this.rutaArchivo = rutaArchivo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_resultado.estado
     *
     * @return the value of tbl_resultado.estado
     *
     * @ibatorgenerated
     */
    public Integer getEstado() {
        return estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_resultado.estado
     *
     * @param estado the value for tbl_resultado.estado
     *
     * @ibatorgenerated
     */
    public void setEstado(Integer estado) {
        this.estado = estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_resultado
     *
     * @ibatorgenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof Resultado)) {
            return false;
        }
        Resultado other = (Resultado) that;
        return this.getId() == null ? other == null : this.getId().equals(other.getId())
            && this.getIdAlumno() == null ? other == null : this.getIdAlumno().equals(other.getIdAlumno())
            && this.getIdCurso() == null ? other == null : this.getIdCurso().equals(other.getIdCurso())
            && this.getNota() == null ? other == null : this.getNota().equals(other.getNota())
            && this.getNumPregCorrectas() == null ? other == null : this.getNumPregCorrectas().equals(other.getNumPregCorrectas())
            && this.getNumPregIncorrectas() == null ? other == null : this.getNumPregIncorrectas().equals(other.getNumPregIncorrectas())
            && this.getCondicion() == null ? other == null : this.getCondicion().equals(other.getCondicion())
            && this.getRutaArchivo() == null ? other == null : this.getRutaArchivo().equals(other.getRutaArchivo())
            && this.getEstado() == null ? other == null : this.getEstado().equals(other.getEstado());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_resultado
     *
     * @ibatorgenerated
     */
    @Override
    public int hashCode() {
        int hash = 23;
        if (getId() != null) {
            hash *= getId().hashCode();
        }
        if (getIdAlumno() != null) {
            hash *= getIdAlumno().hashCode();
        }
        if (getIdCurso() != null) {
            hash *= getIdCurso().hashCode();
        }
        if (getNota() != null) {
            hash *= getNota().hashCode();
        }
        if (getNumPregCorrectas() != null) {
            hash *= getNumPregCorrectas().hashCode();
        }
        if (getNumPregIncorrectas() != null) {
            hash *= getNumPregIncorrectas().hashCode();
        }
        if (getCondicion() != null) {
            hash *= getCondicion().hashCode();
        }
        if (getRutaArchivo() != null) {
            hash *= getRutaArchivo().hashCode();
        }
        if (getEstado() != null) {
            hash *= getEstado().hashCode();
        }
        return hash;
    }
}