package pe.gob.ep.ginnet.radamanthys.bean;

public class Tema {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_tema.id_tema
     *
     * @ibatorgenerated
     */
    private Integer idTema;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_tema.id_curso
     *
     * @ibatorgenerated
     */
    private Integer idCurso;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_tema.tema
     *
     * @ibatorgenerated
     */
    private String tema;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_tema.descripcion
     *
     * @ibatorgenerated
     */
    private String descripcion;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_tema.tipo
     *
     * @ibatorgenerated
     */
    private Integer tipo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_tema.estado
     *
     * @ibatorgenerated
     */
    private Integer estado;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_tema.id_tema
     *
     * @return the value of tbl_tema.id_tema
     *
     * @ibatorgenerated
     */
    public Integer getIdTema() {
        return idTema;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_tema.id_tema
     *
     * @param idTema the value for tbl_tema.id_tema
     *
     * @ibatorgenerated
     */
    public void setIdTema(Integer idTema) {
        this.idTema = idTema;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_tema.id_curso
     *
     * @return the value of tbl_tema.id_curso
     *
     * @ibatorgenerated
     */
    public Integer getIdCurso() {
        return idCurso;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_tema.id_curso
     *
     * @param idCurso the value for tbl_tema.id_curso
     *
     * @ibatorgenerated
     */
    public void setIdCurso(Integer idCurso) {
        this.idCurso = idCurso;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_tema.tema
     *
     * @return the value of tbl_tema.tema
     *
     * @ibatorgenerated
     */
    public String getTema() {
        return tema;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_tema.tema
     *
     * @param tema the value for tbl_tema.tema
     *
     * @ibatorgenerated
     */
    public void setTema(String tema) {
        this.tema = tema;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_tema.descripcion
     *
     * @return the value of tbl_tema.descripcion
     *
     * @ibatorgenerated
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_tema.descripcion
     *
     * @param descripcion the value for tbl_tema.descripcion
     *
     * @ibatorgenerated
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_tema.tipo
     *
     * @return the value of tbl_tema.tipo
     *
     * @ibatorgenerated
     */
    public Integer getTipo() {
        return tipo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_tema.tipo
     *
     * @param tipo the value for tbl_tema.tipo
     *
     * @ibatorgenerated
     */
    public void setTipo(Integer tipo) {
        this.tipo = tipo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_tema.estado
     *
     * @return the value of tbl_tema.estado
     *
     * @ibatorgenerated
     */
    public Integer getEstado() {
        return estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_tema.estado
     *
     * @param estado the value for tbl_tema.estado
     *
     * @ibatorgenerated
     */
    public void setEstado(Integer estado) {
        this.estado = estado;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_tema
     *
     * @ibatorgenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof Tema)) {
            return false;
        }
        Tema other = (Tema) that;
        return this.getIdTema() == null ? other == null : this.getIdTema().equals(other.getIdTema())
            && this.getIdCurso() == null ? other == null : this.getIdCurso().equals(other.getIdCurso())
            && this.getTema() == null ? other == null : this.getTema().equals(other.getTema())
            && this.getDescripcion() == null ? other == null : this.getDescripcion().equals(other.getDescripcion())
            && this.getTipo() == null ? other == null : this.getTipo().equals(other.getTipo())
            && this.getEstado() == null ? other == null : this.getEstado().equals(other.getEstado());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_tema
     *
     * @ibatorgenerated
     */
    @Override
    public int hashCode() {
        int hash = 23;
        if (getIdTema() != null) {
            hash *= getIdTema().hashCode();
        }
        if (getIdCurso() != null) {
            hash *= getIdCurso().hashCode();
        }
        if (getTema() != null) {
            hash *= getTema().hashCode();
        }
        if (getDescripcion() != null) {
            hash *= getDescripcion().hashCode();
        }
        if (getTipo() != null) {
            hash *= getTipo().hashCode();
        }
        if (getEstado() != null) {
            hash *= getEstado().hashCode();
        }
        return hash;
    }
}