package pe.gob.ep.ginnet.radamanthys.dao.ibatis;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.ginnet.radamanthys.bean.Alumno;
import pe.gob.ep.ginnet.radamanthys.bean.AlumnoCriteria;
import pe.gob.ep.ginnet.radamanthys.dao.AlumnoDAO;

public class AlumnoDAOImpl extends SqlMapClientDaoSupport implements AlumnoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_alumno
     *
     * @ibatorgenerated
     */
    public AlumnoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_alumno
     *
     * @ibatorgenerated
     */
    public int countByExample(AlumnoCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tbl_alumno.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_alumno
     *
     * @ibatorgenerated
     */
    public int deleteByExample(AlumnoCriteria example) {
        int rows = getSqlMapClientTemplate().delete("tbl_alumno.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_alumno
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer id) {
        Alumno key = new Alumno();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tbl_alumno.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_alumno
     *
     * @ibatorgenerated
     */
    public void insert(Alumno record) {
        getSqlMapClientTemplate().insert("tbl_alumno.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_alumno
     *
     * @ibatorgenerated
     */
    public void insertSelective(Alumno record) {
        getSqlMapClientTemplate().insert("tbl_alumno.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_alumno
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<Alumno> selectByExample(AlumnoCriteria example) {
        List<Alumno> list = getSqlMapClientTemplate().queryForList("tbl_alumno.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_alumno
     *
     * @ibatorgenerated
     */
    public Alumno selectByPrimaryKey(Integer id) {
        Alumno key = new Alumno();
        key.setId(id);
        Alumno record = (Alumno) getSqlMapClientTemplate().queryForObject("tbl_alumno.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_alumno
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(Alumno record, AlumnoCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_alumno.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_alumno
     *
     * @ibatorgenerated
     */
    public int updateByExample(Alumno record, AlumnoCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_alumno.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_alumno
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(Alumno record) {
        int rows = getSqlMapClientTemplate().update("tbl_alumno.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_alumno
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(Alumno record) {
        int rows = getSqlMapClientTemplate().update("tbl_alumno.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_alumno
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends AlumnoCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, AlumnoCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}