package pe.gob.ep.ginnet.radamanthys.dao.ibatis;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import pe.gob.ep.ginnet.radamanthys.bean.Docente;
import pe.gob.ep.ginnet.radamanthys.bean.DocenteCriteria;
import pe.gob.ep.ginnet.radamanthys.dao.DocenteDAO;

public class DocenteDAOImpl extends SqlMapClientDaoSupport implements DocenteDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_docente
     *
     * @ibatorgenerated
     */
    public DocenteDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_docente
     *
     * @ibatorgenerated
     */
    public int countByExample(DocenteCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tbl_docente.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_docente
     *
     * @ibatorgenerated
     */
    public int deleteByExample(DocenteCriteria example) {
        int rows = getSqlMapClientTemplate().delete("tbl_docente.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_docente
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer idDocente) {
        Docente key = new Docente();
        key.setIdDocente(idDocente);
        int rows = getSqlMapClientTemplate().delete("tbl_docente.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_docente
     *
     * @ibatorgenerated
     */
    public void insert(Docente record) {
        getSqlMapClientTemplate().insert("tbl_docente.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_docente
     *
     * @ibatorgenerated
     */
    public void insertSelective(Docente record) {
        getSqlMapClientTemplate().insert("tbl_docente.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_docente
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<Docente> selectByExample(DocenteCriteria example) {
        List<Docente> list = getSqlMapClientTemplate().queryForList("tbl_docente.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_docente
     *
     * @ibatorgenerated
     */
    public Docente selectByPrimaryKey(Integer idDocente) {
        Docente key = new Docente();
        key.setIdDocente(idDocente);
        Docente record = (Docente) getSqlMapClientTemplate().queryForObject("tbl_docente.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_docente
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(Docente record, DocenteCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_docente.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_docente
     *
     * @ibatorgenerated
     */
    public int updateByExample(Docente record, DocenteCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_docente.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_docente
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(Docente record) {
        int rows = getSqlMapClientTemplate().update("tbl_docente.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_docente
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(Docente record) {
        int rows = getSqlMapClientTemplate().update("tbl_docente.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_docente
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends DocenteCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, DocenteCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}