package pe.gob.ep.ginnet.radamanthys.dao.ibatis;

import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.ginnet.radamanthys.bean.Persona;
import pe.gob.ep.ginnet.radamanthys.bean.PersonaCriteria;
import pe.gob.ep.ginnet.radamanthys.dao.PersonaDAO;

public class PersonaDAOImpl extends SqlMapClientDaoSupport implements PersonaDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_persona
     *
     * @ibatorgenerated
     */
    public PersonaDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_persona
     *
     * @ibatorgenerated
     */
    public int countByExample(PersonaCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tbl_persona.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_persona
     *
     * @ibatorgenerated
     */
    public int deleteByExample(PersonaCriteria example) {
        int rows = getSqlMapClientTemplate().delete("tbl_persona.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_persona
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer codigo) {
        Persona key = new Persona();
        key.setCodigo(codigo);
        int rows = getSqlMapClientTemplate().delete("tbl_persona.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_persona
     *
     * @ibatorgenerated
     */
    public void insert(Persona record) {
        getSqlMapClientTemplate().insert("tbl_persona.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_persona
     *
     * @ibatorgenerated
     */
    public void insertSelective(Persona record) {
        getSqlMapClientTemplate().insert("tbl_persona.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_persona
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<Persona> selectByExample(PersonaCriteria example) {
        List<Persona> list = getSqlMapClientTemplate().queryForList("tbl_persona.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_persona
     *
     * @ibatorgenerated
     */
    public Persona selectByPrimaryKey(Integer codigo) {
        Persona key = new Persona();
        key.setCodigo(codigo);
        Persona record = (Persona) getSqlMapClientTemplate().queryForObject("tbl_persona.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_persona
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(Persona record, PersonaCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_persona.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_persona
     *
     * @ibatorgenerated
     */
    public int updateByExample(Persona record, PersonaCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_persona.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_persona
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(Persona record) {
        int rows = getSqlMapClientTemplate().update("tbl_persona.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_persona
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(Persona record) {
        int rows = getSqlMapClientTemplate().update("tbl_persona.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_persona
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends PersonaCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, PersonaCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public Persona validateUser(Map<String, Object> params) throws Exception {
		// TODO Auto-generated method stub
		Persona persona = new Persona();
		persona = (Persona) getSqlMapClientTemplate().queryForObject("tbl_persona.selectPersona", params);
		return persona;
	}

	
}