package pe.gob.ep.ginnet.radamanthys.dao.ibatis;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.ginnet.radamanthys.bean.ProfesorCurso;
import pe.gob.ep.ginnet.radamanthys.bean.ProfesorCursoCriteria;
import pe.gob.ep.ginnet.radamanthys.dao.ProfesorCursoDAO;

public class ProfesorCursoDAOImpl extends SqlMapClientDaoSupport implements ProfesorCursoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_profesor_curso
     *
     * @ibatorgenerated
     */
    public ProfesorCursoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_profesor_curso
     *
     * @ibatorgenerated
     */
    public int countByExample(ProfesorCursoCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tbl_profesor_curso.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_profesor_curso
     *
     * @ibatorgenerated
     */
    public int deleteByExample(ProfesorCursoCriteria example) {
        int rows = getSqlMapClientTemplate().delete("tbl_profesor_curso.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_profesor_curso
     *
     * @ibatorgenerated
     */
    public void insert(ProfesorCurso record) {
        getSqlMapClientTemplate().insert("tbl_profesor_curso.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_profesor_curso
     *
     * @ibatorgenerated
     */
    public void insertSelective(ProfesorCurso record) {
        getSqlMapClientTemplate().insert("tbl_profesor_curso.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_profesor_curso
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<ProfesorCurso> selectByExample(ProfesorCursoCriteria example) {
        List<ProfesorCurso> list = getSqlMapClientTemplate().queryForList("tbl_profesor_curso.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_profesor_curso
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(ProfesorCurso record, ProfesorCursoCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_profesor_curso.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_profesor_curso
     *
     * @ibatorgenerated
     */
    public int updateByExample(ProfesorCurso record, ProfesorCursoCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_profesor_curso.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_profesor_curso
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends ProfesorCursoCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, ProfesorCursoCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}