package pe.gob.ep.ginnet.radamanthys.dao.ibatis;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.ginnet.radamanthys.bean.Prueba;
import pe.gob.ep.ginnet.radamanthys.bean.PruebaCriteria;
import pe.gob.ep.ginnet.radamanthys.dao.PruebaDAO;

public class PruebaDAOImpl extends SqlMapClientDaoSupport implements PruebaDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prueba
     *
     * @ibatorgenerated
     */
    public PruebaDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prueba
     *
     * @ibatorgenerated
     */
    public int countByExample(PruebaCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tbl_prueba.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prueba
     *
     * @ibatorgenerated
     */
    public int deleteByExample(PruebaCriteria example) {
        int rows = getSqlMapClientTemplate().delete("tbl_prueba.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prueba
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer idNombre) {
        Prueba key = new Prueba();
        key.setIdNombre(idNombre);
        int rows = getSqlMapClientTemplate().delete("tbl_prueba.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prueba
     *
     * @ibatorgenerated
     */
    public void insert(Prueba record) {
        getSqlMapClientTemplate().insert("tbl_prueba.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prueba
     *
     * @ibatorgenerated
     */
    public void insertSelective(Prueba record) {
        getSqlMapClientTemplate().insert("tbl_prueba.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prueba
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<Prueba> selectByExample(PruebaCriteria example) {
        List<Prueba> list = getSqlMapClientTemplate().queryForList("tbl_prueba.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prueba
     *
     * @ibatorgenerated
     */
    public Prueba selectByPrimaryKey(Integer idNombre) {
        Prueba key = new Prueba();
        key.setIdNombre(idNombre);
        Prueba record = (Prueba) getSqlMapClientTemplate().queryForObject("tbl_prueba.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prueba
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(Prueba record, PruebaCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_prueba.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prueba
     *
     * @ibatorgenerated
     */
    public int updateByExample(Prueba record, PruebaCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_prueba.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prueba
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(Prueba record) {
        int rows = getSqlMapClientTemplate().update("tbl_prueba.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_prueba
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(Prueba record) {
        int rows = getSqlMapClientTemplate().update("tbl_prueba.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_prueba
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends PruebaCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, PruebaCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}