package pe.gob.ep.ginnet.radamanthys.dao.ibatis;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.ginnet.radamanthys.bean.Resumen;
import pe.gob.ep.ginnet.radamanthys.bean.ResumenCriteria;
import pe.gob.ep.ginnet.radamanthys.dao.ResumenDAO;

public class ResumenDAOImpl extends SqlMapClientDaoSupport implements ResumenDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_resumen
     *
     * @ibatorgenerated
     */
    public ResumenDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_resumen
     *
     * @ibatorgenerated
     */
    public int countByExample(ResumenCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tbl_resumen.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_resumen
     *
     * @ibatorgenerated
     */
    public int deleteByExample(ResumenCriteria example) {
        int rows = getSqlMapClientTemplate().delete("tbl_resumen.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_resumen
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer id) {
        Resumen key = new Resumen();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tbl_resumen.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_resumen
     *
     * @ibatorgenerated
     */
    public void insert(Resumen record) {
        getSqlMapClientTemplate().insert("tbl_resumen.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_resumen
     *
     * @ibatorgenerated
     */
    public void insertSelective(Resumen record) {
        getSqlMapClientTemplate().insert("tbl_resumen.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_resumen
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<Resumen> selectByExample(ResumenCriteria example) {
        List<Resumen> list = getSqlMapClientTemplate().queryForList("tbl_resumen.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_resumen
     *
     * @ibatorgenerated
     */
    public Resumen selectByPrimaryKey(Integer id) {
        Resumen key = new Resumen();
        key.setId(id);
        Resumen record = (Resumen) getSqlMapClientTemplate().queryForObject("tbl_resumen.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_resumen
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(Resumen record, ResumenCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_resumen.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_resumen
     *
     * @ibatorgenerated
     */
    public int updateByExample(Resumen record, ResumenCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_resumen.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_resumen
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(Resumen record) {
        int rows = getSqlMapClientTemplate().update("tbl_resumen.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_resumen
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(Resumen record) {
        int rows = getSqlMapClientTemplate().update("tbl_resumen.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_resumen
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends ResumenCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, ResumenCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}