package pe.gob.ep.ginnet.radamanthys.dao.ibatis;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.ginnet.radamanthys.bean.Resultado;
import pe.gob.ep.ginnet.radamanthys.bean.ResultadoCriteria;
import pe.gob.ep.ginnet.radamanthys.dao.ResultadoDAO;

public class ResultadoDAOImpl extends SqlMapClientDaoSupport implements ResultadoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_resultado
     *
     * @ibatorgenerated
     */
    public ResultadoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_resultado
     *
     * @ibatorgenerated
     */
    public int countByExample(ResultadoCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("tbl_resultado.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_resultado
     *
     * @ibatorgenerated
     */
    public int deleteByExample(ResultadoCriteria example) {
        int rows = getSqlMapClientTemplate().delete("tbl_resultado.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_resultado
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer id) {
        Resultado key = new Resultado();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("tbl_resultado.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_resultado
     *
     * @ibatorgenerated
     */
    public void insert(Resultado record) {
        getSqlMapClientTemplate().insert("tbl_resultado.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_resultado
     *
     * @ibatorgenerated
     */
    public void insertSelective(Resultado record) {
        getSqlMapClientTemplate().insert("tbl_resultado.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_resultado
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<Resultado> selectByExample(ResultadoCriteria example) {
        List<Resultado> list = getSqlMapClientTemplate().queryForList("tbl_resultado.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_resultado
     *
     * @ibatorgenerated
     */
    public Resultado selectByPrimaryKey(Integer id) {
        Resultado key = new Resultado();
        key.setId(id);
        Resultado record = (Resultado) getSqlMapClientTemplate().queryForObject("tbl_resultado.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_resultado
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(Resultado record, ResultadoCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_resultado.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_resultado
     *
     * @ibatorgenerated
     */
    public int updateByExample(Resultado record, ResultadoCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("tbl_resultado.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_resultado
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(Resultado record) {
        int rows = getSqlMapClientTemplate().update("tbl_resultado.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_resultado
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(Resultado record) {
        int rows = getSqlMapClientTemplate().update("tbl_resultado.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_resultado
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends ResultadoCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, ResultadoCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public int getLastResultado() {
		// TODO Auto-generated method stub
		Integer maxId = (Integer)  getSqlMapClientTemplate().queryForObject("tbl_resultado.getLastResultado");
        return maxId;
	}

	@Override
	public void updateResultadoById(Map<String, Object> params) {
		// TODO Auto-generated method stub
		getSqlMapClientTemplate().update("tbl_resultado.updateResultadoById", params);
		
	}

	@Override
	public List<Map<String, Object>> mostrarResultadoExamen(Map<String, Object> params) {
		// TODO Auto-generated method stub
		List<Map<String, Object>> list = getSqlMapClientTemplate().queryForList("tbl_resultado.getAllResultadosExamen", params);
		return list;		
	}

	@Override
	public void actualizarNotaExamen(Map<String, Object> params) {
		// TODO Auto-generated method stub
		getSqlMapClientTemplate().update("tbl_resultado.actualizarNotaExamen", params);
	}
    
    
}