package pe.gob.ep.ginnet.ruedanegocio.dao.ibatis;


import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import pe.gob.ep.ginnet.ruedanegocio.bean.Proyecto;
import pe.gob.ep.ginnet.ruedanegocio.bean.ProyectoCriteria;
import pe.gob.ep.ginnet.ruedanegocio.dao.ProyectoDAO;

public class ProyectoDAOImpl extends SqlMapClientDaoSupport implements ProyectoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WILLIAN.CTRL_MANT_PROYECTO
     *
     * @ibatorgenerated
     */
    public ProyectoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WILLIAN.CTRL_MANT_PROYECTO
     *
     * @ibatorgenerated
     */
    public int countByExample(ProyectoCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("WILLIAN_CTRL_MANT_PROYECTO.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WILLIAN.CTRL_MANT_PROYECTO
     *
     * @ibatorgenerated
     */
    public int deleteByExample(ProyectoCriteria example) {
        int rows = getSqlMapClientTemplate().delete("WILLIAN_CTRL_MANT_PROYECTO.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WILLIAN.CTRL_MANT_PROYECTO
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(Integer idProyecto) {
        Proyecto key = new Proyecto();
        key.setIdProyecto(idProyecto);
        int rows = getSqlMapClientTemplate().delete("WILLIAN_CTRL_MANT_PROYECTO.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WILLIAN.CTRL_MANT_PROYECTO
     *
     * @ibatorgenerated
     */
    public void insert(Proyecto record) {
        getSqlMapClientTemplate().insert("WILLIAN_CTRL_MANT_PROYECTO.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WILLIAN.CTRL_MANT_PROYECTO
     *
     * @ibatorgenerated
     */
    public void insertSelective(Proyecto record) {
        getSqlMapClientTemplate().insert("WILLIAN_CTRL_MANT_PROYECTO.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WILLIAN.CTRL_MANT_PROYECTO
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<Proyecto> selectByExample(ProyectoCriteria example) {
        List<Proyecto> list = getSqlMapClientTemplate().queryForList("WILLIAN_CTRL_MANT_PROYECTO.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WILLIAN.CTRL_MANT_PROYECTO
     *
     * @ibatorgenerated
     */
    public Proyecto selectByPrimaryKey(Integer idProyecto) {
        Proyecto key = new Proyecto();
        key.setIdProyecto(idProyecto);
        Proyecto record = (Proyecto) getSqlMapClientTemplate().queryForObject("WILLIAN_CTRL_MANT_PROYECTO.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WILLIAN.CTRL_MANT_PROYECTO
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(Proyecto record, ProyectoCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("WILLIAN_CTRL_MANT_PROYECTO.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WILLIAN.CTRL_MANT_PROYECTO
     *
     * @ibatorgenerated
     */
    public int updateByExample(Proyecto record, ProyectoCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("WILLIAN_CTRL_MANT_PROYECTO.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WILLIAN.CTRL_MANT_PROYECTO
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(Proyecto record) {
        int rows = getSqlMapClientTemplate().update("WILLIAN_CTRL_MANT_PROYECTO.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table WILLIAN.CTRL_MANT_PROYECTO
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(Proyecto record) {
        int rows = getSqlMapClientTemplate().update("WILLIAN_CTRL_MANT_PROYECTO.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table WILLIAN.CTRL_MANT_PROYECTO
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends ProyectoCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, ProyectoCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}